### ISSUE TITLE
[MariaDelas]W3-pipelines-project

### ISSUE THREAD

**Issue by mariadelascotrina** [Ironhack-Data-Madrid-Octubre-2021/W3-pipelines-project#1]

**Comment by mariadelascotrina** [comment]
https://github.com/mariadelascotrina/02.MariaDelas-W3-pipelines-project.git

**Comment by yamadajc** [comment]
Hola hola Maria!
Voy a intentar darte todo el feedback con la intención de que realices un cambio positivo, para que mejores todo lo posible.


## README

Poco tengo que decirte sobre el redame. Me apetece seguir leyendo. Tan solo decirte que no hace falta que pongas import pandas. Si pones pandas y pones el enlace a la documentación estaría. 

Con un pequeño toque de manutención hubieses hecho con markdown estaría de 10. Te dejo una guía de los markdown  👉 [aquí](https://www.markdownguide.org/cheat-sheet/) 

## Estructura del repo

Esta genial. Tienes la estructura que debería tener todo repo. Hubiese estado bien tener una carpeta `Notebooks` y meter dentro una division de cada fase de `Brecha_salarial&personalidad.ipynb` en distintos jupyter.

 ❤️❤️❤️❤️tu `.gitignore` ❤️❤️❤️❤️

## Sintaxis de código

Para la FASE 1 y el "problemita" que tuviste con el nombre de los países te dejo el patron de regex para que pruebes `\s[A-Z][a-z]+` 😉

El resto todo bien. Un gustazo leer tu código y ver unas gráficas. Recuerda que el objetivo de este proyecto era generar un script capaz de leer y completar información de varias fuentes. Para luego generar un archivo que puedas consumir. Y tu `main.py ` solo me esta devolviendo **GRÁFICO 2**.


## ToDo
Tu trabajo es muy bueno. Me tienes que hacer un main.py que refleje todo tu savoir faire.

Gracias por trabajazo ❤️
