### ISSUE TITLE
[w3-pipelines-project] Andres Perez

### ISSUE THREAD

**Issue by Andrestart** [Ironhack-Data-Madrid-Octubre-2021/W3-pipelines-project#10]
https://github.com/Andrestart/Pipeline.git

**Comment by AnaAGG** [comment]
# Proyecto Pipeline 

Hola hola Andrés 🙋🏻‍♀️ ya estoy por aquí otra vez! Pero esta vez te vengo a contar cositas sobre tu proyecto de pipelines 🚀.

## README
Bueno Andrés, en general me ha encantado tu readme, muy bien sintetizado todo el trabjo y con un buen uso del *markdown*. Te dejo por aquí unos *tips* para que los podamos ir incorporando en los futuros readmes: 

- Cuentas que APIs y datos has usado, pero no cual es el objetivo del proyecto. 
  - ¿Por qué coges esos datos?
  - ¿Qué preguntas o hipótesis quieres contestar? 
- Has puesto un link a la página de la Comunidad de Madrid para descargarse los datos 👏🏽. Para que que quedara TOP TOP, lo que podemos hacer es crear un "link" usando el *markdown* 

    ¿Cómo podemos hacer esto en markdown? 
    ```
    [dataset](https://datos.madrid.es/)
    # Si haces esto verás algo como esto 👇🏽 en el readme
    ```
    [dataset](https://datos.madrid.es/)
- Lo ideal que pusieras el link también a la documentación de la API que has usado

Por el resto, todo suuper bien. Me encanta el *worklow* de trabajo que incluiste en este proyecto Andrés. 

## Estructura del repo
Suuper bien estructurado tu trabajo Andrés. Aún así, te dejo por aquí unos *tips* por si te aportan valor en el futuro: 

- Tienes dos carpetas donde guardas imagenes, `images` y `saved_graphs`. Lo ideal es que fueran todas en una única carpeta y que ya ahi las separaras. 

- Suuper bien porque no se te pasó ningún fichero rarinchi fuera del  `.gitignore`

- En este proyecto no tenemos muchos jupyters notebooks, pero en un futuro nos podemos encontrar con que si. Para que nuestro repo quedé más organizado lo que puedes hacer es crearte una carpeta que se llame `notebooks` y vayas almacenando ahí los jupyters. Si además los numeras para saber cual es el *workflow* de trabajo te quedarís suuuuper top!


## Sintaxis de código

### main 

- Vamos al código que tienes cuando cargas los datos. Haces el `read_csv` y luego haces `pd.DataFrame`. Pero... esto tiene sentido? El método `read_csv` ya nos devuelve un dataframe. Por lo tanto, en este caso con que hicieramos el `read_csv` ya sería suficiente, no hace falta convertirlo a dataframe. 

    ```python
    # este es tu código
    ac = pd.read_csv('data/2020_Accidentalidad.csv', sep=';')
    ac = pd.DataFrame(ac)

    # como lo podríamos dejar
    ac = pd.read_csv('data/2020_Accidentalidad.csv', sep=';') # con esto ya tenemos el dataframe
    ```
- Lo mismo aquí, si hacemos un subdataframe de un dataframe ya existente no hace falta que lo convirtamos a dataframe

    ```python
    newac = pd.DataFrame(ac[['fecha','num_expediente']])  

    # en este caso de nuevo no hace falta que incluyamos el pd.DataFrame por que el subset ya nos devuelve el dataframe. Por lo tanto, el código quedaría más o menos así: 

    newac = ac[['fecha','num_expediente']] # con esto seleccionamos solo las columnas que nos interesan.
    ```

- Suuper bien los *docstrings* en las funciones Andrés. Está perfectísimas!

- Tienes una función que te cambia el formato de tus fechas, lo cual esta suuper bien. Solo por si te aporta valor, usando la librería `datetime` tenemos un método propio que nos lo hace

    ```python
    str_time = datetime.strftime(date_time, '%Y-%m-%d')
    # ⚠️ pero este método solo nos funcionara si tu columna es de formato datetime. Siempre lo podemos cambiar. 
    ```
    Te dejo por [aqui](https://docs.python.org/3/library/datetime.html) algo de docu. 

- Super bien reemplazando los valores nulos por la media de las columna 🔝🔝
- Enorme haciendo también la visualización en el `main.py` Andrés! Solo me voy a poner un poco quisquillosa con una cosa, en el main tienes el código que guarda las imagenes comentado. Dejalo sin comentar y si hay alguna actualización en los datos se verá automaticamente en las gráficas que nos descargemos. 

    > Tuviste algún problema con esto? Si es así dime y lo vemos juntos 😉. 
- En cuanto al jjupyter de las visualizaciones, esta increíble. No solo has hecho las gráficas si no que has hecho una gran interpretación de los datos 👏🏽

## TODOs

Bueno Andrés, en general tienes un trabajo espectacular en este proyecto. Te dejo por aquí una especie de *recap* de lo que te comenté: 

- En el readme meter un poco más de info sobre la API que usaste y los datos. 
- Siempre nos podemos crear la carpeta de `notebooks` para meter ahí los jupyters. 
- Revisar librería `datetime` es una fantasía y tiene millones de funcionalidades para trabajar con fechas. 


Bueno Andrés, poco más que decirte, trabajo INCREIBLE 🔥🔥! 

![image](https://user-images.githubusercontent.com/75084991/142994558-0fa7eab6-20aa-4256-9b21-e5fdacddf59f.png)
