### ISSUE TITLE
[Proyecto 2] - Nicolás Ponce

### ISSUE THREAD

**Issue by NicolasPce** [Ironhack-Data-Madrid-Octubre-2021/W3-pipelines-project#11]
https://github.com/NicolasPce/P-2

**Comment by AnaAGG** [comment]
# Proyecto Pipeline

Hola hola Nico 🙋🏻‍♀️ ya estoy por aquí otra vez! Pero esta vez te vengo a contar cositas sobre tu proyecto de pipelines 🚀.

## README

Tienes el objetivo del proyecto y nos cuentas que dos tipos de fuentes has usado, además también has incluido las librerías que has usado con los links a la documentación oficial. Suuper top Nico! 

Vamos con algunos detallines de cara al futuro por si te aportan valor: 

- Utilizas un dataframe de kaggle, lo que podemos hacer en este caso es poner el link a la página de kaggle de donde nos lo podemos descargar.

- Lo mismo con la página que escrapeas, pon el link en el readme para que sepamos  cual es la fuente de datos.

- Estaría bien que hicieras un pequeño resumen de los datos que obtendríamos de cada una de las fuentes de datos. A modo de *recap* y que es lo que te añade *scrapear*  a tu proyecto. 

- Tal vez para este proyecto no sea tan importante, pero de cara al futuro. Nuestros repos cada vez tendrán más ficheros y carpetas, por esto, suele ser recomendable poner la estructura de las carpetas que tenemos y explicar que nos podemos encontrar en cada una de ellas. 

- Esto es más una pijería que otra cosa, pero cuando haces la lista de las librerías te quedaron todas en una línea. Lo ideal que lo pongamos como lista. 

## Estructura del repo

Vamos con la estructura! 

- Cuidado con los archivos temporales que se nos crean en el proyecto. Por ejemplo el `.DS_Store`, tienes uno dentro de la carpeta data, otro en la página principal rel repo y otro dentro de la carpeta `JN`. Además tienes un `__pycache__` dentro del `src`. Todos estos ficheros deben ir al `.gitignore` ya que son archivos temporales que no son importantes para el proyecto. 

- En el `src` tienes un fichero que se llama `funcionesp2.py`, evitamos poner nombres tan generales en los ficheros, lo ideal es poner nombres que sean autoexplicativos. 

- En la carpeta de `JN` tienes metida una imagen, lo ideal que nos creemos una carpeta que se llame `images` por ejemplo donde guardemos allí todas las imagenes que vamos a necesitar o nos creemos en el proyecto. 

- Tienes un par de ficheros dentro de `JN` que se llaman Test. Supongo que son los jupyters donde hiciste las pruebas para el main. Esta guay que los tengas, pero ya que son unos jupyters que están un poco desordenados y que son simplemente para testear, lo ideal sería que estuvieran en el `.gitignore` para que nadie los vea. 

- Tines el fichero de `Visuals` fuera de la carpeta jupyters, en este caso yo lo metería también ahí. La idea tener todos los jupyters en una carpeta. 

    Además, en caso de que tengamos varios jupyters, lo ideal sería que los numeraramos. Con esta quedaría suuuuper TOP!

Menuda turra te he dado Nico, pero en general son detallines, por ponerme un poco pijotera😂

## Sintaxis de código

Vamos con la parte de código 🚀

- Las funciones que tienes, tienes un *docstring*, peeero lo tienes fuera de la función 😔. Supongo que esto ya te lo dirían en la primera corrección pero te dejo por aquí unos *tips* de como hacer un *docstring* 

   ¿Qué es lo que tiene que tener un docstring?   
        - Qué es lo que hace la función  
        - Qué argumentos recibe  
        - Qué es lo que devuelve
        - Y lo más importante es que tiene que estar dentro de la función.   

    [Aquí](https://www.python.org/dev/peps/pep-0257/) algo de info sobre los docstrings . 

    ```python
    def mifuncion(argumento1, argumento2):
        '''
        Lo que hace la función
        args: 
            argumento1: tipo de dato
            argumento2: tipo de dato
        return:
            que nos devuelve la función
        '''
        return "Hola"
    ```

- Suuper bien que incluyeras la visualización dentro del main.py Nico 👏🏽! 

- En la parte de la visualización, super sacas una gráfica y la interpretas, buen trabajo Nico!

- Solo como detalle, en el jupyter de la visualización tienes la explicación en una celda de código donde le pones una # para que no te ejecute. Recuerda que en jupyuter tenemos la opción de crear celdas de markdown en las que podremos escribir todo lo que queramos! 

La verdad es que poco más te puedo decir, tienes un código muy bien sintetizado y bien documentado

## TODOs

Bueno Nico, en general el proyecto esta bastante completo. Has incorporado datos a un dataset que ya teníamos. Te dejo por aquí un pequeño resumen sobre los comentarios que te hice. Principalmente están relacionados con el readme y la estrucutra del repo. 

- Podemos estructurar un poquito mejor el repo, con los ficheros metidos en las carpetas correspondientes. Y sobre todo, esos archivos temporales! 
- Los *docstrings* en las funciones
- Más info en el readme

Bueno Nico, la parte de código esta impecable, buen trabajo! Seguimosssss 🚀

![image](https://user-images.githubusercontent.com/75084991/143012611-abaf2745-0e89-4cb1-a09a-42985c6b4f1d.png)
