### ISSUE TITLE
[proyecto semana 3] Fernando Zapico

### ISSUE THREAD

**Issue by 4tolon** [Ironhack-Data-Madrid-Octubre-2021/W3-pipelines-project#12]
https://github.com/4tolon/TheLinkedinProject

No he podido finalizar, mi cerebro de robot ha petado. Readme para mas info. No perdais el tiempo examinando el codigo, esta sucio y no me da la vida para limpiarlo, si quereis os lo explico sobre mi pc.

**Comment by yamadajc** [comment]
# Proyecto Pipeline
Hola Fernando!

Menuda fantasia te has marcado. Me queda claro que tienes un absoluto dominio de kugfu del markdown.

Sé que has tenido que enferentarte a muchos problemas. Has hecho un gran trabajo y has luchado como un jabato. Aun así el proyecto no esta completo. 

Entiendo que antes de primavera podrás sacar un hueco para poner las tildes y darle otro aspecto. Pero te ruego que mantenga la misma energía 🙏 porque es maravillosa. 

Animo y a seguir con esa actitud!
