### ISSUE TITLE
[Blanca Vispo] W3-pipelines-project

### ISSUE THREAD

**Issue by bvispo** [Ironhack-Data-Madrid-Octubre-2021/W3-pipelines-project#13]
https://github.com/bvispo/Proyecto-Pipeline

**Comment by AnaAGG** [comment]
# Proyecto Pipeline Blanca

Hola hola Blanca 🙋🏻‍♀️ ya estoy por aquí otra vez! Pero esta vez te vengo a contar cositas sobre tu proyecto de pipelines 🚀.

## README
Buenisimo readme Blanca! Has hecho una gran descripción de todos los datos que sacas,puesto los links a la documentación o los csv, has puesto también las librerías que has usado y su link a la documentación oficial 🔝. 

Solo me ha faltado un detallín en este readme: 

- Hubiera quedado genial que pusieras la estructura que nos encontramos en el repo, de una forma esquemática.  
  - ¿Qué carpetas tenemos? 
  - ¿Qué nos podemos encontrar en cada carpeta? 

Por el resto, nada más que decirte. Enhorabuena por el readme 🥳

## Estructura del repo

Muy bien organizado y compartimentado el repo Blanca. Te dejo aquí un par de comentarios por si te aportan valor 😊:

- Se nos ha pasado un archivo temporal, el `.DS_Store` en la carpeta de `data`

- Tienes una imagen dentro de carpeta Notebooks, lo ideal es que la movieras a la carpeta que tienes de `images`

## Sintaxis de código

### Vamos allá con la parte de código del pipeline:

- En la función de `drop_columns` tienes una pequeña erratilla:

    ```python
    def drop_columns ():
        """
        This function drops columns.
        Arggs: columns to be droppped.
        Returns: new dataframe
        """
        return df_smart.drop(["Id", "SmartCity_Index_relative_Edmonton"], axis=1, inplace=True)
    # 🔴 ojo aquí, tienes puesto que tu función recibe un argumento, que es las columnas que quieres eliminar, pero sin embargo no tiene ningún parámetro cuando la defines. Debería ser de la siguiente forma:
    def drop_columns (cols):
        """
        This function drops columns.
        Arggs: columns to be droppped.
        Returns: new dataframe
        """
        return df_smart.drop(["Id", "SmartCity_Index_relative_Edmonton"], axis=1, inplace=True)
    ```
- En el fichero `pipeline.py` tienes imports en mitad del código. Por convención hay que ponerlos al incio del fichero, para que nada más empezar sepamos que librerías voy a necesitar. 

- Te falta el *docstring* en algunas funciones, aunque sean facilitas, hay que ponerlos😉
- Vamos con la parte donde cambias los nombres de los continentes, que además tienes una pregunta donde pones como hacer esto de una: 

    ```python
    # este es el código que tenías tu
    smart["Continent"] = smart["Continent"].str.replace("NA", "North America")
    smart["Continent"] = smart["Continent"].str.replace("OC", "Oceania")
    smart["Continent"] = smart["Continent"].str.replace("EU", "Europe")
    smart["Continent"] = smart["Continent"].str.replace("AS", "Asia")

    # te acuerdas en el proyecto de tiburones cuando limpiabamos la columna de `species`? Pues en este caso podríamos hacer algo similar: 

    def clean_continent(x):
        diccionario = {"OC": "Oceania",
                        "EU": "Europe" ...}

        for key, value in diccionario.items():
            if key in x:
                return x.replace(key, value)
            else:
                return x

     smart["Continent"] = smart["Continent"].apply(clean_continent) # y encima sin hacer regex! 
    # 🔴 Esto es pseudocódigo, no lo he probado en jupyter, pero los tiros deben ir por aquí. 
    ```
### Vamos ahora con la visualización:
- Venga, me voy a poner quisquillosa con este jupyter. Tienes unas funciones que se llamas `getTop10Cities` ,  `getWorst10Cities` , `overal_getWorst10Cities` y `overal_getTop10Cities` en el jupyter. Create un `.py` nuevo para la visualización e importala desde allí. Y RECUERDA LOS DOCSTRINGS 🤓! 

- Me hubiera gustado que en las gráficas que sacas de `getWorst10Cities` y `getTop10Cities` me añadieras algo de explicación, donde me interpretaras lo que vemos en las gráficas y a que a puede ser debido.


## TODOs

Bueno Blanca, has hecho un buenísimo trabajo en este proyecto la verdad. Casi todas las correcciones que te hice son detalles para cerrar el proyecto y que te quede TOP TOP. Como siempre, te hago aquí un pequeño recap de las principales ideas que te dejé por aquí:

- Los *docstrings* en las funciones! 
- Atomizar algunas partes del código
- Explicar y justificar el por qué de algunas de las gráficas que sacaste
- Los archivos temporales que se nos generas al `.gitignore`

Enorme Blanca, lo estás petando muy fuerte 💪🔥🔥🔥🔥. 

![image](https://user-images.githubusercontent.com/75084991/143203108-5d247811-f2be-400c-acf8-bc126673a379.png)
