### ISSUE TITLE
[Ana Walsh] W3-pipelines-project

### ISSUE THREAD

**Issue by AnaWalsh** [Ironhack-Data-Madrid-Octubre-2021/W3-pipelines-project#14]
https://github.com/AnaWalsh/W3-pipelines-project.git

**Comment by yamadajc** [comment]
# Proyecto Pipeline
Hola Ana,
Voy a intentar darte todo el feedback con la intención de que realices un cambio positivo, para que mejores todo lo posible.
¡¡Vamos a ello !!

## README

El readme esta correcto. Me dices cuales la estructura del repo, indicas también el objetivo que es el de verificar la hipótesis ... obviamente 😂. También me hablas del conjunto de datos e incluso me has puesto un enlace a la fuente. 

Si haces lo siguiente podrás incrustar un enlace en un copy.
```
[Concentración global de CO2 atmosférico](https://ourworldindata.org/grapher/monthly-atm-co2?country=~OWID_WRL)
```

Si haces esto verás algo como esto 👇🏽 en el readme
[Concentración global de CO2 atmosférico](https://ourworldindata.org/grapher/monthly-atm-co2?country=~OWID_WRL)

Y podrías hacer lo mismo con las librerías usadas enlazándo a la documentación de las mismas.

## Estructura del repo

La estructura esta genial. Me has creado varios directorios y su contenido esta bien organizado como por ejemplo el de los notebooks. 

Otro apunte. El `__pycache__` del directorio `src` mételo en el `.gitignore`.


## Sintaxis de código

Esta muy bien. Me estas facilitando mucho la vida con tus docstring. Tienes un código muy limpio, pero te dejo un par de comentarios para mejorar. 

¿Sabias que `sys.path.append('/Users/awalsh/Ironhack/PROYECTOS/W3-pipelines-project/src')` es lo mismo que `sys.path.append('../src')` ? Es exactamente lo mismo pero queda mas limpio y si algun compi de terabajo intenta replicarlo le sera mas facil 😉. 


Ojo con los nombres de las funciones van en minuscula y el de las clases en mayúscula. 

`getAverageOceanTemperatureByDecade` 🤔

`average_on_decade`🤗


## ToDo

Muy bien. Un trabajo claro y conciso. Si acaso le hubiese puesto una gráfica al readme... ya que las creas enseñalas y dame fantasia. 

❤️ Gracias ❤️
