### ISSUE TITLE
[W3 Pipeline Project] María Pérez de Ayala

### ISSUE THREAD

**Issue by mariaperezdeayalas** [Ironhack-Data-Madrid-Octubre-2021/W3-pipelines-project#16]
https://github.com/mariaperezdeayalas/E-Commerce-Shipping-Pipelines-Project-

**Comment by Fominayasg** [comment]
## Buenas Maria !! :smile:

El objetivo de este proyecto era ser capaces de crear un `pipeline`. Es decir, una secuencia de `procesos` que se ejecutaran en orden para que ,en nuestro caso, desde un dataframe original obtener otro limpio y enriquecido.

Ahora vamos a ir viendo los diferentes componentes de tu proyecto.

## Readme

En un archivo markdown no hace falta que pongas un `#` para comenzar una nueva línea. Solamente se pone delante de los títulos y pondremos más o menos `#` en función de la jerarquía de títulos.

Para cambiar de línea hay que dar dos intros, es decir dejar una línea libre entre párrafo y párrafo.

En cuanto a formato yo dejaría algo así:

---
```markdown
# E-Commerce-Shipping-Pipelines-Project-

![foto de un almacen](almacen.png)

 In this project I wanted to get myself into a real company case, analyzing the logistics part of a business and getting conclusions around customer satisfaction and logistics efficiency.

 For it, I have taken a dataset from Kaggles called "E-Commerce Shipping Data", which gave me the logistics data of an international e-commerce company that sells electronic devices.

## **Data questions / hypotheses:**
 The first 2 questions / hypotheses are around the shipment efficiency and logistics part:
 1. What is the most effective mode of shipment? 
 2. Is there a specific warehouse block which is giving the business more issues? 
 While the last 2 questions are linked to customer satisfaction and loyalty: 
 3. For those products considered with high importance, what is the rating we have from our customers on those?
 4. How many loyal customers do we have? Those with 5 or more prior purchases, do they give the company a higher rating? Also, do we offer them more discounts?

 ## **API:**
 As the dataset was of a specific company, I have not found an API to enrich the dataset directly.
 However, I have found an API called "Order-Tracking" which gives me all delivery options I have around the world. With the help of it I have created a table with all the options so the company can search for courier companies across the entire globe. 

 ## **Web Scraping:**
 To enrich more the project, I have used Web Scraping to give the company a potential app partner for its deliveries. 
 With this partner the company would avoid have that many customer care calls with all their orders.

 ## **Conclusion & Learnings:**
 In this dataset the info was evenly spread across all the key figures so I have not been able to get a specific conclusion neither improvement for the company.
 However, this has allowed me to see how would it be to work on this for a real case in a business, by doing an analysis of a dataset and then enriching it with an API & web scraping.
 ```
---
 Que se vería así:

# E-Commerce-Shipping-Pipelines-Project-

![foto de un almacen](almacen.png)

 In this project I wanted to get myself into a real company case, analyzing the logistics part of a business and getting conclusions around customer satisfaction and logistics efficiency.

 For it, I have taken a dataset from Kaggles called "E-Commerce Shipping Data", which gave me the logistics data of an international e-commerce company that sells electronic devices.

## **Data questions / hypotheses:**
 The first 2 questions / hypotheses are around the shipment efficiency and logistics part:
 1. What is the most effective mode of shipment? 
 2. Is there a specific warehouse block which is giving the business more issues? 

 While the last 2 questions are linked to customer satisfaction and loyalty: 

 3. For those products considered with high importance, what is the rating we have from our customers on those?
 4. How many loyal customers do we have? Those with 5 or more prior purchases, do they give the company a higher rating? Also, do we offer them more discounts?

 ## **API:**
 As the dataset was of a specific company, I have not found an API to enrich the dataset directly.
 However, I have found an API called "Order-Tracking" which gives me all delivery options I have around the world. With the help of it I have created a table with all the options so the company can search for courier companies across the entire globe. 

 ## **Web Scraping:**
 To enrich more the project, I have used Web Scraping to give the company a potential app partner for its deliveries. 
 With this partner the company would avoid have that many customer care calls with all their orders.

 ## **Conclusion & Learnings:**
 In this dataset the info was evenly spread across all the key figures so I have not been able to get a specific conclusion neither improvement for the company.
 However, this has allowed me to see how would it be to work on this for a real case in a business, by doing an analysis of a dataset and then enriching it with an API & web scraping.

---
Respecto al contenido del readme:

El proyecto está bien descrito pero me fatarían la estructura del repo y el technology stack.

En cuanto a la organización del repo no es más que poner unos cuantos bullet points diciendo que hay en cada carpeta.

Para las tecnologías utilizadas, te recomiendo que incluyas los links de está manera:

```markdown
In this project we have used the following libraries:
 - [pandas](https://pandas.pydata.org/docs/)
 
 - [numpy](https://numpy.org/doc/stable/)
 
 - [plotly](https://plotly.com/python/)
 
 - [seaborn](https://seaborn.pydata.org/)
 
 - our own "[cleaning_functions.py](https://url_de_mi_archivito.py)"
```

Y te quedaría asi:

In this project we have used the following libraries:
 - [pandas](https://pandas.pydata.org/docs/)
 
 - [numpy](https://numpy.org/doc/stable/)
 
 - [plotly](https://plotly.com/python/)
  
 - [seaborn](https://seaborn.pydata.org/)
 
 - our own "[cleaning_functions.py](https://url_de_mi_archivito.py)"


## Organización del repo

**.gitignore**

Se te han colado varios archivos temporales en el repo, como por ejemplo el archivo `.DS_Store` que se genera al abrir una carpeta en MacOS. Estos archivos los debes meter lo primero de todo en el gitognore para que no se suban a GitHub. Si se te suben a Github, y luego los mestes en el .gitignore, no funcionará.

**csv**

tienes full.csv repetido dentro de `data`y eln la carpeta raíz. no están actualizados en el mismo commit así que no sé si son archivos diferentes o si son el mismo archivo. de cualquier manera, si tienes una carpeta llamada `data`, lo suyo es que todos los archivos de datos estén dentro.

**Imágenes**

Tu carpeta principal del repo debe estar lo más limpia posible. Cuando quieras subir archivos de imágenes (ya sea para la portada o porue has exportado visualizaciones por ejemplo) puedes incluirlos en una carpeta `images` o incluso en `data`.

**Notebooks**

Genial que los hayas metido todos en una carpeta, si además los numeras para que el lector sepa cual es el orden de ejecución ya lo bordas.

## Cleaning

Está genial que hayas comentado el jupyter, aunque porfi... No me pongas todo como título (`# `delante) que es un poco doloroso de leer.

En cuanto a la limpieza has hecho más bien un trabajo de reinterpretación de variables (tu dataset ya estaba limpio). 

La reinterpretación está my bien pensada de cara a tu problema de negocio, aunque quizá pondría categorías con nombres más sencillos. Por ejemplo:
- "Loyal"/"not loyal" --> valores 0 o 1 en función de si es leal o no
- percentage range --> categorias low/medium/high por ejemplo, en vez de poner toooodo el porcentaje.

## Enriquecimiento


Has utilizado tanto la técnica de scraping como la de API para enriquecer tu dataset. Genial! Pero...
¿¿Llegas a relacionarlo con tus datos originales de alguna manera??

El objetivo del enriquecimiento es que tu análisis sea más preciso y que tu dataset sea más relevante.

Aunque no hacía falta que incluyas lso datos en el propio dataset si que habría sido interesante que en el análisis incluyas esta info.

## Pipeline

El pipeline es sencillo pero está bien contruido. Puedes intentar añadir funciones de visualización


Ser apaz de encontrar un dataset usable y enriquecerlo para hacer finalmente un análisis no es fácil, pero si le das una vuelta más y mejoras los detallitos que te he puesto arriba te quedará un proyecto muy chulo porque es un caso muy real.

¡A tope! :rocket:
