### ISSUE TITLE
[W3-pipelines-project] Pedro Martínez

### ISSUE THREAD

**Issue by pedromartinezleis** [Ironhack-Data-Madrid-Octubre-2021/W3-pipelines-project#17]
https://github.com/pedromartinezleis/Project-Movies

**Comment by Fominayasg** [comment]
Muy buenas Pablitooo :stuck_out_tongue_winking_eye:!!!

El objetivo de este proyecto era ser capaces de crear un `pipeline`. Es decir, una secuencia de `procesos` que se ejecutaran en orden para que ,en nuestro caso, desde un dataframe original obtener otro limpio y enriquecido.

Ahora vamos a ir viendo los diferentes componentes de tu proyecto.

## Readme
Como ya sabes el readme es vuestra carta de presentación y por tanto es importante prestarle atención.

Tu readme describe tu proyecto pero le falta un poco de estructura. Puedes hacer algo así:

1. Utilizar el formato markdown. [Aquí](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) está una guía de como escribir en markdown.Es importante utilizar títulos, bullet points, listas, etc. Le dará un aspecto mucho más profesional al readme.
2. Ordénalo en secciones.
    - Contexto resumido (max 5 lineas)
    - Objetivo del proyecto (1 frase)
    - Origen de los datos
    - Organización del repo (Qué hay en cada carpeta)
    - Tecnologías utilizadas
3. Para las tecnologías utilizadas, te recomiendo que incluyas los links de está manera:

```markdown
In this project we have used the following libraries:
 - [pandas](https://pandas.pydata.org/docs/)
 
 - [numpy](https://numpy.org/doc/stable/)
 
 - [plotly](https://plotly.com/python/)
 
 - [seaborn](https://seaborn.pydata.org/)
 
 - our own "[cleaning_functions.py](www.link_a_tu_archivo_py.es)"
```

Y te quedaría asi:

In this project we have used the following libraries:
 - [pandas](https://pandas.pydata.org/docs/)
 
 - [numpy](https://numpy.org/doc/stable/)
 
 - [plotly](https://plotly.com/python/)
  
 - [seaborn](https://seaborn.pydata.org/)
 
 - our own "[cleaning_functions.py](www.link_a_tu_archivo_py.es)"

## Estructura del repo

Ya que tienes una carpeta `data`, aprovéchala y mete dentro todos los csv. 

Así te quedará la página pricipal de tu repo más ordenada.

veo que se te han colado algunos archivos `__pycache__`. Estos mejor mételos en el gitognore para que no se suban. No aportan valor a tu proyecto y ocupan espacio en github.


## Cleaning y enriquecimiento
Tienes un token en el jupyter con un mensaje al lado que pone:

`#.env por diooooooooos(mensaje de Sonia)`

ejem ejem...


Has enriquiecido un poco tu info con la api de imbd pero deberías incluir ese enriquecimiento en tu pipeline.


## Visualización

En este jupyter deberían estar única y exclusivamente los plots y su explicación.

Las modificaciones de los dataset deben ir en cleaning y/o en el `main.py`.

Por otro lado has utilizado la funcion `cl.cambioBudget`pero no has importado tu archivo de funciones en el jupyter...

Está genial que hayas buscado la correlación entre budget y metascore. Pero hay que explicarlo un poco más:
```Dada la baja correlación entre la valoración de las películas y su presupuesto, podemos decir que, al menos en las películas de Christopher Nolan, no es cierto que a mayor preupuesto mejor valoración```

Por otro lado, esta frase no se puede poner en un informe de análisis de datos:

```La película de abajo a la derecha tiene un presupuesto de 6000 dólares, por eso aparece encima del cero.```

¿Qué es abajo a la derecha?(De hecho creo que te refieres a abajo¿Cómo que aparece encima del cero?

La explicación tiene que ser más amplia y utilizar un lenguaje más riguroso.

Podrías decir algo como:

``` Nota : informativa: La película de menor presupuesto, se corresponde con un importe de 6000 dólares por lo que como nuestro gráfico está midiendo en cientos de millones de dólares, se corresponde con el valor cero en el eje X```

Faltan más visualizaciones que nos den info sobre tus datos (aunque tengas pocos), alguna visualización sobre el dataset enriquecido... alguna comparación entre ambos... o alguna otra idea que se te ocurra.

No nos sirve de nada incorporar más datos si luego no lo aprovechamos en nuestro análisis.

Pedro este proyecto está bastante incompleto pero con lo que has aprendido hasta ahora y siguiendo un poco lo que te he comentado en el feedback seguro que lo dejas de lujo.
