### ISSUE TITLE
BeaSánchez[Proyecto_APIS]

### ISSUE THREAD

**Issue by Beapsp** [Ironhack-Data-Madrid-Octubre-2021/W3-pipelines-project#18]
https://github.com/Beapsp/Proyecto_APIS.git

**Comment by yamadajc** [comment]
# Proyecto Pipeline
Hola Bea,
Voy a intentar darte todo el feedback con la intención de que realices un cambio positivo, para que mejores todo lo posible.
¡¡Vamos a ello !!

## README
Tu readme esta super, pero te dejo algunos consejos para mejorar.

- El readme estaría de 10 si me usases correctamente el markdow 👉 [aqui](https://www.markdownguide.org/cheat-sheet/) te dejo una guía. 

- Cuando pongas enlaces revisa que te lleven a donde tu quieres. Hay alguno que parece no funcionar.


## Estructura del repo

Es interesante crear directorios para cada tipo de archivo como por ejemplo para las fotos. 
Pero la estructura esta genial. Has creado varios directorios y pero si numeras el contenido intenta que siga un orden. 

Recuerda actualizar tu `.gitignore` para evitar que se te cuelen archivos, como las apikey por no meterlas en el `.env`, entre otras. 

## Sintaxis de código

El código esta muy clarito y eso los comentarios son de agradecer. Por cierto eso de hacer una llamada a la API via lista de ingredientes para crear tu `df_clean` ... ❤️❤️❤️ PURA CREATIVIDAD ❤️❤️❤️

Me despido de ti diciéndote que has hecho un buen trabajo y con tu maravilloso print infinito de mas de 67300 lineas  que no me cabe  😜.
