### ISSUE TITLE
[LYDIA] W3-pipelines-project

### ISSUE THREAD

**Issue by Lydia-Arocena** [Ironhack-Data-Madrid-Octubre-2021/W3-pipelines-project#19]
https://github.com/Lydia-Arocena/PROYECTO-2-APIS

**Comment by AnaAGG** [comment]
# Proyecto Pipeline 

Hola hola Lydia 🙋🏻‍♀️ ya estoy por aquí otra vez! Pero esta vez te vengo a contar cositas sobre tu proyecto de pipelines 🚀.

## README

Bueno Lydia, la verdad es que tienes un readme de libro. Tengo bastante poco que decirte, por no decirte que nada, pero ya sabes que siempre alguna cosa os decimos: 

- Cuando pones los links de las páginas oficiales donde descargarse el `csv` y la info de la API: 

    Si ya me lo pones como un link de markdown, me rindo a tus pies 😂!T Te dejo aquí como lo podíamos hacer: 

    ```
    [dataset](https://www.kaggle.com/.)
    ```
    Y en el link que pones, es el general de kaggle, pon el específico del csv que usas. 

- Cuando hablas de la estructura del repo, suuper bien. Solo como detalle, tanto el `.gitignore` como el `.env` no hace falta que los nombremos en esta parte. Esto es una pijería, pero por si te aporta valor. 

Por el resto todo perfectito Lydia, buenísimo trabajo! 

## Estructura del repo
Bueno, de nuevo, el repo esta suuper bien organizado Lydia. Te dejo un par de detalles de tiquismiquis, pero en computo general, trabajo perfecto: 

- Dentro de la carpeta `Notebooks` tienes otra carpeta que se llama `borradores` que supongo que será donde fuiste haciendo tus pruebitas. Dado que tienes todo tu código en todos los archivos `.py` y son borradores, los puedes meter en el `.gitignore` para que nadie vea tu pruebitas. 
  
- Tienes por ahí una imagen suelta, aunque sea solo una, te puedes crear una carpeta que se llame `images` donde vayas almacenando todas las imagenes que necesites para el proyecto o que vayas generando. 

## Sintaxis de código

- Solo como detalle, en los *docstrings*, cuando tenemos una función que no recibe parámetros también tenemos que ponerlo en el *docstrings*. Podemos poner algo como esto: 

    ```
    Esta función sirve para cargar el csv.
    Parámetros: 
        No recibe parámetros
    Return:
         df del csv importado.
    ```
- Vamos a la parte que renombras las columnas de tu `csv`. Tienes este código: 

    ```python
    for_city = {'UA_Name': 'City'}
    df.rename(columns=for_city,inplace=True)
    for_country= {'UA_Country': 'Country'}
    df.rename(columns=for_country,inplace=True)
    for_continent= {'UA_Continent': 'Continent'}
    df.rename(columns=for_continent,inplace=True)

    #  te creas tres diccionarios diferentes y aplicas el método rename tres veces... esto me pone triste 😂. Recuerda que lo podemos hacer en un único diccionario. El código quedaría más o menos así: 

    new_columns = {'UA_Name': 'City', 'UA_Country': 'Country', 'UA_Continent': 'Continent'}
    df.rename(columns=for_country,inplace=True)

    ```

- La verdad Lydia, es que no te puedo decir mucho más. Tienes un trabajo impecable. 

Como reto te dejo por aquí esta idea.... Meter el código de los mapas en funciones! Para que me puedas sacar los mapas para cualquier cosa!

## TODOs
Bueno Lydia, increíble el trabajo que he visto en este proyecto. Tu evolución ha sido increíble. Te dejo recap de las principales cosas de la correción, aunque son detalles

- Crear los links a la docu oficial tanto de tus datos como de las librerías. Si quieres lo vemos juntas. 


- Acuérdate, cuando tenemos mucho código repetido es que lo podemos hacer de otra forma más eficaz.  


Sigue trabajando así Lydia, lo estás petanto muy muy fuerte 💪🔥🔥🔥

![image](https://user-images.githubusercontent.com/75084991/143233478-13d0b71e-af78-4428-b69d-7ab181e91f76.png)
