### ISSUE TITLE
[w3 Pipeline] Alfonso Romero

### ISSUE THREAD

**Issue by aromegar** [Ironhack-Data-Madrid-Octubre-2021/W3-pipelines-project#2]
https://github.com/aromegar/Pipeline.git

**Comment by AnaAGG** [comment]
# Proyecto Pipeline

Hola hola Alfonso 🙋🏻‍♀️ ya estoy por aquí otra vez! Pero esta vez te vengo a contar cositas sobre tu proyecto de pipelines 🚀.

## README

En general el readme esta muy bien Alfonso, bastante completo con la estructura de las carpetas que encontraremos en el repo, el objetivo, que es lo que hace tu ejecutable y algunos links a las APIs que has usado. 

¿Qué me ha faltado o que podríamos incluir para darle un poco más de valor al readme? 

- Las librerías que has usado con los links a la documetación oficial a cada una de ellas. 
  
- Un poco más de detalle sobre lo que nos devolvía cada API que has usado en el proyecto

- Falta el link a una de las API, en concreto a la de Amadeus.

## Estructura del repo

En general la estructura del repo esta perfecta Alfonso. Solo un par de detalles por si te aportan valor en el futuro: 

- Se nos ha pasado un archivo temporal fuera del `.gitignore`, el `__pycache__`. Recuerda, cualquier fichero que no queramos ver o cualquier archivo temporal que se nos cree (como el `__pycache__`) lo debemos meter dentro del `.gitignore`. 

- Solo como detalle, en este repo la estructura no es muy compleja, pero en proyectos fucturos nos encontraremos con más jupyters por ejemplo. En ese caso lo ideal es que nos creemos una carpeta que se llame `Notebooks` donde los almacenemos. Si los numeramos para saber el orden de trabajo quedaría TOP TOP

- No he visto el archivo `.gitignore` por lo que supongo que no lo tendrás en el repo. Recuerda que este es imprescindible para guardar ahí todos los ficheros que no queremos que se vean. 


## Sintaxis de código

Lo primerito de todo, enhorabuena has hecho el ejecutable (`main.py`) y de una forma espectacular. Partiendo de esta base, te dejo por aquí algunos comentarios por si te aportan valor: 

### main 

- En cuanto a los *docstrings*, suuper bien que los hayas incluido en todas tus funciones 👏🏽. Solo como detalle de cara al futuro, ¿cómo podríamos rematar estos *docstrings*?

    ¿Qué es lo que tiene que tener un docstring?   
        - Qué es lo que hace la función  
        - Qué argumentos recibe  
        - Qué es lo que devuelve  

    [Aquí](https://www.python.org/dev/peps/pep-0257/) algo de info sobre los docstrings . 

    ```python
    def mifuncion(argumento1, argumento2):
        '''
        Lo que hace la función
        args: 
            argumento1: tipo de dato
            argumento2: tipo de dato
        return:
            que nos devuelve la función
        '''
        return "Hola"
    ```
- Esto es más una pijería, pero te la comenta por si las moscas. Por convención, las funciones deben ir con minúscula y las clases es mayúscula. En tu caso, en el fichero de `api_functions.py` tienes algunas funciones en mayúscula como por ejemplo (`Amad` o `W_fc3`)

- Vamos con al función `coordenadas` que tienes en el `dataset_functions.py`. Con esta función lo que buscas en redondear los valores de una columna a dos decimales. En este caso, esta función no tendría mucho sentido ya que tenemos un método propio que nos permite hacer esto. Siempre que tengamos un método propio no es aconsejable crearse una función. 

    ¿Cómo podríamos entonces hacer esto en pandas? 

    ```python
    # en caso de que se lo queramos aplicar a una única columna
    df["coord"] = round(df["coord"], 2)

    # en caso de que se lo queramos aplicar a dos o más columas
    df[["col1", "col2"]] = round(df[["col1","col2"]], 2)
    ```
- Cuando haces la transformación a *float* de un par de las columnas, haces lo siguiente:

    ```python
    df["precio_ida"] = df["precio_ida"].astype(dtype="float64")
    df["precio_vuelta"] = df["precio_vuelta"].astype(dtype="float64")

    # esto también lo podemos hacer en una única línea de código
    df[["precio_ida", "precio_vuelta"]] = df[["precio_ida", "precio_vuelta"]].astype(dtype="float64")
    ```
- En relación a la segunda llamada a la API, la de los datos climatológicos. Si te fijas, repites la misma estructura de código para los tres días que sacas. Esto es viable porque solo lo haces para tres días. Pero imagínate que lo tuvieramos que hacer de 50 días. Podría ser un poco doloroso. 

    ¿Cómo podríamos solucionar esto?

    Creándonos una función que nos devuelva los datos climatológicos para todos los días que queramos.

    ```python
    #tu código es este
    df["day0"]=df.apply(lambda fila : [fila["datos"][0]["day"]["maxtemp_c"],
                                   fila["datos"][0]["day"]["mintemp_c"],
                                   fila["datos"][0]["day"]["daily_chance_of_rain"],
                                   fila["datos"][0]["day"]["condition"]["text"],
                                   fila["datos"][0]["day"]["condition"]["icon"]], axis=1)

    # definimos la función de limpieza
    def clean_climate(x,  num):
        [x["datos"][num]["day"]["maxtemp_c"],
        x["datos"][num]["day"]["mintemp_c"],
        x["datos"][num]["day"]["daily_chance_of_rain"],
        x["datos"][num]["day"]["condition"]["text"],
        x["datos"][num]["day"]["condition"]["icon"]]
        return x
    # aplicamos la función para los tres dias, sin repetir la estructura de código
    df["day0"]=df.apply(lambda fila : clean_climate(fila, 0), axis=1)

    # PD 🚨 Esto es pseudo-código. No lo he probado en un jupyter y no garantizo que funcione al 100%, pero por aquí deben ir los tiros. 
    ```
### Visuals
- Ojo en la función `ordenadito`, el *docstring* puede ser algo confuso ya que pones en los argumentos que recibe 3, pero luego especificas que son 3 listas y un *string*. Es una pijotada, pero es por que tu proyecto quede completamente cerradito! 
    ```python
    def ordenadito(city,d0,d1,d2):
        """
        Argumentos: 3 listas 🔴
        Recibe 1 str y 3 listas y me forma un dataframe ordenadito. 🔴
        edit: me estaba cogiendo las listas como string, las reconvierto a lista
        """
        d0 = ast.literal_eval(d0)
        d1 = ast.literal_eval(d1)
        d2 = ast.literal_eval(d2)
            
        diccio = {city : ["T_max", "t_min", "prob_lluvia", "tiempo", "icono"],
                    "d0" : d0,
                    "d1" : d1,
                    "d2" : d2}

        return pd.DataFrame(diccio)
    
    ```
- Tienes un par de visualizaciones interesantes en esta parte Alfonso, por ponerme un poco tiquismiquis, me faltado que me cuentes un poco que es lo que estamos viendo en las visualizaciones que hiciste. Dame un poco de *strorytelling* 😂

- Por último, tienes una función, `dibujar` que la tienes definida en el `.py` pero no la usas en el jupuyter. En este caso, mi recomendación no incluirla el el fichero. 

    ```python
    def dibujar(tit):
        """
        dibuja una imagen a partir de un titulo
        """
        url = f"http:{tit}"
        response = requests.get(url)
        img = Image.open(BytesIO(response.content))
        return img
    ```
## TODOs

Bueno Alfonso, en general has hecho un trabajo impecable en este proyecto. Te dejo por aquí un pequeño recap con algunas de las principales cosas que podríamos cambiar de cara al futuro: 

- Los *docstrings* 
- Eliminar aquellas partes de código que no usamos
- Atomizar partes de código que tenemos muy repetidas
- Un poquito de *storytelling*, véndeme tu historia! 


Trabajazo Alfonso!!!! Sigue así, estás haciendo un trabajo impecable 🔥🔥🔥

![image](https://user-images.githubusercontent.com/75084991/142943675-fec19790-d27e-4409-b9f6-994f11be7193.png)
