### ISSUE TITLE
[W3-pipelines] Andrés Uzcátegui

### ISSUE THREAD

**Issue by baccandres** [Ironhack-Data-Madrid-Octubre-2021/W3-pipelines-project#20]
https://github.com/baccandres/Spotify-Pipeline.git

**Comment by baccandres** [comment]
No logré finalizar el pipeline. Me gustaría entenderlo mejor en clase!

**Comment by Fominayasg** [comment]
## Buenas Andrés !! :smile:

El objetivo de este proyecto era ser capaces de crear un `pipeline`. Es decir, una secuencia de `procesos` que se ejecutaran en orden para que ,en nuestro caso, desde un dataframe original obtener otro limpio y enriquecido.

Ahora vamos a ir viendo los diferentes componentes de tu proyecto.

## Readme

Tu archivo `README.md`  se llama `READ ME.md`por lo tanto github no lo reconoce como readme y no te lo está poniendo como portada del repo.

Esto lo solucionas simplemente cambiando el nombre del archivo.

Por otro lado, el readme siempre te va a quedar más profesional si le metes un poquito de formato `markdown`

[Aquí](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) está una guía de como escribir en markdown.Es importante utilizar títulos, bullet points, listas, etc. Le dará un aspecto mucho más profesional al readme.

En cuanto al contenido, te falta añadir el technolgy stack. Puedes hacerlo así:

```markdown
In this project we have used the following libraries:
 - [pandas](https://pandas.pydata.org/docs/)
 
 - [numpy](https://numpy.org/doc/stable/)
 
 - [plotly](https://plotly.com/python/)
 
 - [seaborn](https://seaborn.pydata.org/)
 
 - our own "[cleaning_functions.py](www.link_a_tu_archivo_py.es)"
```

Y te quedaría asi:

In this project we have used the following libraries:
 - [pandas](https://pandas.pydata.org/docs/)
 
 - [numpy](https://numpy.org/doc/stable/)
 
 - [plotly](https://plotly.com/python/)
  
 - [seaborn](https://seaborn.pydata.org/)
 
 - our own "[cleaning_functions.py](www.link_a_tu_archivo_py.es)"

## Estructura del repo

Sw te han colado varios archivos que deberian estar en el gitignore (.DSStore, __pycache__, etc) Es mportante incluirlos en el git ignore al principio del todo porque una vez que se han subido ya no funciona meterlos en el gitignore.

En cuanto a los jupyters estaría bien numerarlos para saber cual va primer y cual después. Yo los metería además en una carpeta todos juntos ya que en el caso de este proyecto, todo lo que primero pruebes en los jupyters debería ir incluido después en el main.py.

Por otro lado los archivos de fnciones deben ir metidos por convenio dentro de una carpeta llamada src.

## Limpieza de datos y enriquecimiento

El objetivo principal de este proyecto es conseguir automatizar los procesos de lipiezar y enriquecimiento pero para ello primero tienes que crear funciones que luego meteras en un archivo.py del cual irás importante funciones en tu pipeline...

Has creado varias funciones y las has iimportado perfectamente en los jupyter notebook. Ahora tratar de encadenar esas funciones juntos con algo ás de código en main.py, de tal manera que cuando lo ejecutes directamente coja el csv o json que a i te interesa lo enriquezca, lo limpie y lo exporte ya listo para la visualización o incluso genere las visualizacines y las exporte.

El jupyter notebook procura comentarlo para que sea más fácil de entender.

# Visualización y conclusiones
Se ve que has trabajado mucho en el análisis de tus datos aunque me falta un poco de explicación más detallada de los gráficos que has generado.

Por ejemplo en el primer gráfico no sé que es q1 q2 q3 y q4. Para verlo me tengo que poner a rebuscar en otros notebooks.

Los últimos scatter plots son muy pequeños y cuesta apreciar los ejes y titulos. Está genial poder compararlos así, uno al lado del otro, pero cuesta un poco. 

Aquí también estaría bien que te extendieras un poco más en la explicación.

La conclusión final está genial, concisa, clara aporta valor teniendo en cuenta la temática de tu proyecto. ¡Enhorabuena!

En resumen, el proyecto va por buen camino, el enriquecimiento es interesante y aporta valor, pero te falta terminar de hacer el pipeline.

Un vez hecho esto estará listo!!
