### ISSUE TITLE
[W3-pipeline] José Díaz

### ISSUE THREAD

**Issue by TheIronhidex** [Ironhack-Data-Madrid-Octubre-2021/W3-pipelines-project#21]
https://github.com/TheIronhidex/Proyect-3

**Comment by AnaAGG** [comment]
# Proyecto Pipeline 

Hola hola José 🙋🏻‍♀️ ya estoy por aquí otra vez! Pero esta vez te vengo a contar cositas sobre tu proyecto de pipelines 🚀.

Lo primerito de todo, perdón por entregar esta revisión tan tarde 😔

## README

Tienes muy bien documentado el readme Jose, enhorabuena. Pero ya sabes que siempre tenemos algo que comentar 😂:

- Por ponerme quisquillosa, en el apartado de `Resources` tienes también cual es la estructura y organización del repo. Esta super bien que lo incluyas, pero en este caso yo lo pondría en un apartado diferente. 

- Me ha falto un apartado con las librerías que has usado y el link a la documentación oficial. 

Dos detallines de nada 😉

## Estructura del repo

Tienes el código super bien modularizado 👏🏽, solo unos detalles:

- En la parte de los notebooks, si los numeras para saber cual es el orden de trabajo sería perfecto! 

- Se te ha quedado un jupyter fuera de la carpeta de `notebooks`, lo idea, meterlo dentro. 

- No tienes el `.gitignore` por lo que entiendo que todos los archivos y carpetas temporales los has eliminado y listo. Esta no es la mejor forma de trabajar, para eso tenemos el `.gitignore`, fichero esencial en nuestros repos! 

    Si tienes alguna duda de como hacerlo, dime y lo vemos juntos. 

Por el resto todo perdectito Jose, buen trabjoooo 🙌🏽

## Sintaxis de código

- Este tipo de cosas evitamos hacerlas:

    ```python
    df0 = df1
    # tenemos el método `copy`de pandas. Siempre que tengamos un método debemos usarlo
    df0 = df1.copy()
    ```
- Sobre los *docstrings* genial que lo hayas incluido 🔝. Solo como detalle, te dejo por aquí como deberían ser para que queden bien bie:

    ¿Qué es lo que tiene que tener un docstring?   
        - Qué es lo que hace la función  
        - Qué argumentos recibe  
        - Qué es lo que devuelve  

    [Aquí](https://www.python.org/dev/peps/pep-0257/) algo de info sobre los docstrings . 

    ```python
    def mifuncion(argumento1, argumento2):
        '''
        Lo que hace la función
        args: 
            argumento1: tipo de dato
            argumento2: tipo de dato
        return:
            que nos devuelve la función
        '''
        return "Hola"
    ```
- Tienes mucha información de distintos sitios, que luego usas para filtrar y mergear info. Esto esta super bien, pero en tu jupyters es difícil de seguir, intenta documentar mejor tus jupyters. 
- Haces varios `dropna` un tantos radicales. Me explico: 

    ```python
    df_last.dropna(axis=1,how='any',inplace=True)
    ```
    Dropear datos es siempre un sacrrileguio y tienes un montón de columnas con valores númericos. Lo ideal es que uses la media o la mediana para reemplazar esos valores nulos. De esta forma no perderemos datos! 

- Tienes jupyters  que están duplicados, ojo con eso!
- Bueno, en general el proyecto esta bien pero ha faltado una parte esencial. La visualización e interpretación de los resultados.
  
## TODOs

Bueno José buen trabajo, te dejo por aquí un *recap*  con las ideas principales que te dije

- Los *docstrings* en las funciones, darles una vueltina
- Ordenar un poco más los jupyters y sobre todo documentarlos
- La VISUALIZACIÖN
- El `.gitignore`
![image](https://user-images.githubusercontent.com/75084991/144723799-cd152781-9383-442c-95f5-0c4309f17b07.png)
