### ISSUE TITLE
[W3-pipelines-projects] Daniela Arias

### ISSUE THREAD

**Issue by daniela-arias** [Ironhack-Data-Madrid-Octubre-2021/W3-pipelines-project#22]
https://github.com/daniela-arias/Taller_API

**Comment by yamadajc** [comment]
# Proyecto Pipeline
Muy buenas Daniela!

Voy a intentar darte todo el feedback con la intención de que realices un cambio positivo, para que mejores todo lo posible.
¡¡Vamos a ello !!

## README

El readme está muy bien. Me hablas de los objetivos, la estructura de repositorio y dejas claro cuál va a ser el workflow. Además me nombras las librerías que está soltando. Quizás explicar lo que son los NOC hubiese estado bien. Como buen ironhacker he tenido que buscar lo que significaba durante un rato...hehehe. 

Podrías haber nombrado la fuente de los datos y también haber puesto los enlaces de la documentación tal que así. 
```
[pandas](https://pandas.pydata.org/docs/)
```
Si haces eso verás algo como esto 👉 [pandas](https://pandas.pydata.org/docs/) .

## Estructura del repo

La estructura del repo esta genial. Tan solo decirte que hubiese estado de 10 haber creado una carpeta para meter `olympics-1.svg` dentro. 

Por otro lado parece que se te han colado algunas cosas de. `.gitignore`. Es posible que subieras un notebook antes del `.gitignore` y así quedarse en cache al hacer push. 

Pero otra vez ... esta genial ❤️

## Sintaxis de código

¿Qué pasa con `api_functions.py` ?  ¿La llegas a utilizar en algún sitio?
Imagino que en `Dataframe.ipynb` pretendías obtener un df en el que apareciese un recuento de las medallas por países. Pero sin comentarios no se si era esa tu intención.  
Si es lo que querías podrías haberlo hecho con un groupby
```python
data_a.groupby(by=["NOC"]).count()
```
Al final de este notebook no veo qué hayas generado ningún dataset de esta limpieza. 

En `Web.ipynb`has hecho un buen trabajo de scrapeo dando como resultado un dataset con info relevante. 

En el readme me dices que para el jupyter `Visualization.ipynb` vas a hacer un análisis y a exponer resultado, tanto a nivel gráfico como descriptivo. Pero no he visto nada de eso ...¿qué ha pasado?

## ToDo 
Felicidades por el scrapeo. El objetivo de este proyecto era generar un script que combinase distintas fuentes de datos para obtener unos datos nuevos y hacer un analisis de los mismos. 

Deberías revisar los jupyter `Dataframe.ipynb` ,`Visualization.ipynb` y eliminar `api_functions.py` si no lo usas. 

Pero seguro que con un poco de trabajo consigues retocarlo para que quede como podíamos. 

A seguir currando !!!🚀
