### ISSUE TITLE
[Pipelines_proyect] Juan Perez de Ayala

### ISSUE THREAD

**Issue by Juanpda** [Ironhack-Data-Madrid-Octubre-2021/W3-pipelines-project#23]
https://github.com/Juanpda/Pipeline_project-JuanPerezdeAyala.git

**Comment by AnaAGG** [comment]
# Proyecto Pipeline 

Hola hola Juan 🙋🏻‍♀️ ya estoy por aquí otra vez! Pero esta vez te vengo a contar cositas sobre tu proyecto de pipelines 🚀.

## README

Super bien definido el objetivo del proyecto, así como la parte donde especificas la estructura de las carpetas que nos vamos a encontrar en el repo 👏🏽. Además pones las librerías que has usado para sacar el proyecto, lo cual está perfecto. Aún así, te dejo por aquí unos *tips* con algunas cosas que me han faltado por si te aportan valor:

- En la parte de las librerías, si las pones en una lista en vez de todas en una línea será más legible. Además, si le añades el link a la documentación oficial de cada librería quedaría suuper bien. 

    ¿Cómo podemos hacer esto en markdown? 
    ```
    [dataset](https://www.kaggle.com/teajay/global-shark-attacks)
    # Si haces esto verás algo como esto 👇🏽 en el readme
    ```
    [dataset](https://www.kaggle.com/teajay/global-shark-attacks)

- En este proyecto trabajas con un `csv` y con una API. ¿Qué información podemos dar sobre estas fuentes de datos? 
  
  - Poner el link a la documentación de la API, así como el link a la página de kaggle de donde te descargaste los datos. 

  - Qué información nos da cada una de las fuentes de datos. Una pequeña descripción sobre lo que tendremos en cada una de las fuentes de datos. 
- Si tienes alguna hipótesis sobre tus datos, también la puedes poner aquí. 
  
## Estuctura del repo

En cuanto a la estructura del repo la verdad es que esta super bien organizado. Te has creado distintas carpetas donde has ido metiendo todas tus cositas, suuper bien Juan! 

Te dejo por aquí un par de detalles por si te aportan valor de cara al futuro: 

- Podemos crearnos otra carpeta que se llame por ejemplo `notebooks` donde guardemos todos nuestros jupyters. Además, si tienes más de uno lo que podemos hacer es numerarlos para saber cual es el orden de trabajo. 
- El archivo `main.py` donde tienes el ejecutable, por convenio se pone en la base del repo, es decir, a la misma altura que las carpetas de `data` y `src`. 
- Me ha faltado el fichero `.gitignore`, este fichero nos va a permitir ocular aquellos documentos o carpetas que no queramos que se vean. También es esencial para guardar nuestro `.env` donde almacenaremos los token si estamos trabajando con APIs


## Sintaxis de código

Vamos con la parte de código! 

### Pipeline

Me ha dejado un poco desconcertada tu código Juan. Quiero decir, tienes un montón de funciones que estan bien definidas a simple vista, pero no veo que las hayas ejecutado en ninguna parte. Solo tienes tres ficheros con funciones, y mira que tienes cosas interesantes, como funciones que llaman a otras funciones, trabajas mucho con diccionarios lo cual esta suuuper bien...

El tema es que al final tienes una figura de los datos y tienes los ficheros... 🤷🏽‍♂️

Es que no has hecho el push de todo el proyecto y me estoy perdiendo algo 🤔

¿Qué es en realidad lo que te falta en el proyecto? 

- Basicamente un `main.py` donde llamemos a todas las funciones que nos hemos creado para la limpieza de datos 

- Me han faltado los *docstrings* en las funciones. Esto es esencial para que la gente sepa que hace tu función y que parámetros recibe. 

    ¿Qué es lo que tiene que tener un docstring?   
        - Qué es lo que hace la función  
        - Qué argumentos recibe  
        - Qué es lo que devuelve  

    [Aquí](https://www.python.org/dev/peps/pep-0257/) algo de info sobre los docstrings . 

    ```python
    def mifuncion(argumento1, argumento2):
        '''
        Lo que hace la función
        args: 
            argumento1: tipo de dato
            argumento2: tipo de dato
        return:
            que nos devuelve la función
        '''
        return "Hola"
    ```
## TODOs

La verdad es que tengo poco que decirte Juan, tienes código interesante, pero el proyecto algo incompleto e inconexo. No entiendo nada. 

Seguimos 🚀

![image](https://user-images.githubusercontent.com/75084991/143223879-ca77f502-4c9d-4bf9-9a85-4df32b47bfd0.png)
