### ISSUE TITLE
[W3-pipelines-project]Luis Serrano

### ISSUE THREAD

**Issue by LuisSerranoCerame** [Ironhack-Data-Madrid-Octubre-2021/W3-pipelines-project#24]
https://github.com/LuisSerranoCerame/W3-pipelines-project-Luis-Serrano.git

**Comment by yamadajc** [comment]
# Proyecto Pipeline
Muy buenas Luis ,
voy a intentar darte todo el feedback con la intención de que realices un cambio positivo, para que mejores todo lo posible.
¡¡Vamos a ello !!

## README

El readme esta muy bien. es un detalle que lo pongas en español. Me dices que vas a hacer, como la vas a hacer, nombras la tecnología que vas a utilizar y mencionas brevemente los datos. 

Recuerda que si a alguien le interesa el tema y de repente aterriza a tu git quizás quiera reproducir tu proyecto y aprender de el.

¿Como podrías mejorarlo?

- Comenta el origen de los datos. ¿De dónde sacas el csv? 

- Utiliza markdown te dejo una guía 👉 [aquí](https://www.markdownguide.org/cheat-sheet/) 

- Pon los enlaces a la documentación de la tecnología. 

- Podrías hacer secciones y luego dentro de cada una de ellas bulletizar. Recuerda que es como escribir un articulo técnico. 

- En tu proyecto, al tener tantos directorios, te diría que vendría bien una descripción de la estructura del repositorio.

## Estructura del repo
La estructura me han faltado algunas cositas en este proyecto. Te dejo por aquí algunas ideas por si te aportan valor de cara al futuro:

- Ojo con los commits que haces. Yo te diría que hagas otro commit para pisar alguno como "Me voy a casa". Que nunca se sabe quién puede leer tu git. 

- No es recomendable tener archivos con distintas extensiones a la vista. Agrupa los `.py`, `.ipynb`, datos o incluso imagenes de gráficos en carpetas distintas. 

    - Una carpeta de `Notebooks` con los jupyters numerados en el orden que desee que el lector los consuma puede ayudar al orden en nuestro repo. Recuerda no mezclar tipos de archivos que se te ha colado `vb_matches.csv`.

    - Aunque no tengas ninguna función creada, una carpeta `src` es mas que recomendable para tener un notebook limpio donde importemos todas las funciones. 

    - Hubiera estado bien que te crearas una carpeta de `data` donde guardaras todos los datos que importes, cargues o transformes. No entiendo muy bien la carpeta Data. Tienes muchísimos archivos, sube solo datos con los que trabajes. Como por ejemplo `Tinder Millennial Match Rate Dataset.csv`. 

- NO tienes el `.gitignore` en tu repo. Este archivo es esencial (debe ser de lo primero que creemos cuando creamos el repo) ya que en este fichero vamos a almacenar todos los archivos temporales que se nos crean o aquellos archivos que no queremos que se muestren. 

- Tu `main.py` no tiene contenido ... Se te olvido actualizar ?


## Sintaxis de código

El código en si esta bien. Al fin y al cabo has scrapeado las edades y eso lo has conseguido. 

Pero ojo con librerías que importas hay algunas que no las usas como `dotenv` o `time`. Ademas tienes celdas que no hacen nada. Cuidado con la limpieza del jupyter. 

Me divides el df en dos para redondear el valor de las edades y luego mergeas. 


```python
df2 = df1.w_p1_age.round()
df3 = df1.w_p2_age.round()

df4 = pd.merge(df2, df3, left_index=True, right_index=True)
```
si redondeas desde el principio te ahorras cosas😉.

```python
df1 = df[['w_p1_age', 'w_p2_age']].round()
```
También podrías haber cambiando el tipo de los datos. 
```python
df1 = df1.astype(dtype=int,errors='ignore')
```

Hay plots muy interesantes que dan solución a tu problema.

Te has marcado unas gráficas muy buenas. Tienes que seleccionar la que mas se ajuste a la explicación de tu problemática y quitar las que generen ruido.Somos analistas y el ruido es incertidumbre. La tienes así que deja solo esa😎. 


## ToDo

Muy bien Luis hay mucho trabajo subido y me has comparado edades de distintas fuentes. Teníais que crear un script el cual no esta. Creo que te has liado con los push y estarás  conmigo que se nota en la organización del repo. Aun así he visto que hay cosas interesantes.

🚀SEGUIMOS🚀
