### ISSUE TITLE
Silviarico_proyecto2

### ISSUE THREAD

**Issue by silviarico** [Ironhack-Data-Madrid-Octubre-2021/W3-pipelines-project#25]
https://github.com/silviarico/pipeline_proyecto1-2.git

**Comment by Fominayasg** [comment]
Buenas Silvia!! :smile:

El objetivo de este proyecto era ser capaces de crear un `pipeline`. Es decir, una secuencia de `procesos` que se ejecutaran en orden para que ,en nuestro caso, desde un dataframe original obtener otro limpio y enriquecido.

Ahora vamos a ir viendo los diferentes componentes de tu proyecto.

## Readme

El readme es la presentacion de tu proyecto. Será lo que a primera vista hable de tu proyecto. Por tanto es importante cuidarlo y hacer que quien lo vea quiera ver tu proyecto en más detalle.

Puedes hacer lo siguiente:

1. Utilizar el formato markdown. [Aquí](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) está una guía de como escribir en markdown.Es importante utilizar títulos, bullet points, listas, etc. Le dará un aspecto mucho más profesional al readme.
2. Ordénalo en secciones. (Contexto resumido, objetivo del proyecto, organización del repo y  tecnologias utilizadas).

Para las tecnologías utilizadas, te recomiendo que incluyas los links de está manera:

```markdown
In this project we have used the following libraries:
 - [pandas](https://pandas.pydata.org/docs/)
 
 - [numpy](https://numpy.org/doc/stable/)
 
 - [plotly](https://plotly.com/python/)
 
 - [seaborn](https://seaborn.pydata.org/)
 
 - our own "[cleaning_functions.py](https://github.com/aromegar/SharkAttack/blob/main/src/cleaning_functions.py)"
```

Y te quedaría asi:

In this project we have used the following libraries:
 - [pandas](https://pandas.pydata.org/docs/)
 
 - [numpy](https://numpy.org/doc/stable/)
 
 - [plotly](https://plotly.com/python/)
  
 - [seaborn](https://seaborn.pydata.org/)
 
 - our own "[cleaning_functions.py](https://github.com/aromegar/SharkAttack/blob/main/src/cleaning_functions.py)"

# Organización del repo

La organización es un poco caótica. Lo ideal sería que tu repo tuviese una estructura de directorios parecida a esta:

Carpeta principal:
- README.md
- gitignore
- carpeta `src`:
    - archivos de funciones. Por ejemplo: `cleaning_functions.py`
- carpeta `data`
- carpeta `jupyter notebooks`
- main.py (tu pipeline)

Los archivos como el `chromedriver`, el `geckodriver`, etc. no se suelen subir a github.

Los archivos temporales `.ipynb_checkpoints`, `__pycache__` etc.. hay que meterlos en el gitognore n cuanto empieces el proyecto para evitar que se suban a github. Si los metes en el `.gitignore` después de que se hallan subido no funcionará.

# Limpieza  y enriquecimiento de datos

Primero de todo ¡ole! por atreverte a meterte con Selenium sin haberlo visto en clase :clap: :clap: :clap: :clap:

En cuanto a las funciones de limpieza, en la función `modelo` en vez de tantos elif puedes utilizar un diccionario, para que tu función quede un poco más limpia.

Aunque no hayas metido todo en funciones separadas, todo el código de limpieza debe ir en el pipeline.

De todas maneras el enriquecimiento está curradísimo, enhorabuena.

Al ver tus datos me surgen algunas dudas... Los modelos que scrapeas, ¿¿son los mismos del csv pero una nueva version?? ¿Son exactamente iguales pero vemos qué precio tienen 3 años después?

Estaría bien una explicación en algún punto del repo ya sea el readme, en comentarios... o donde consideres oportuno.
# Análisis y conclusiones

Al principio del todo pones `en este kernel, visualizamos los datos para determinar más fácilmente si la marca nike a subido sus precios con respecto a 2018` ¿a qué te refieres con "en este kernel"? Supongo al notebook.

El segundo y tercer gráfico no se ven en github. segurate de dejar las celdas runneadas cuando hagas push para que se vea. 

Yo me lo he clonado para corregirlo pero un recruiter no se va a tomar ese tiempo o incluso a lo mejor no sabe clonar un repositorio.

El primer gráfico explica claramente que en general los precios de casi todos los productos han subido. Puede aprovecjhar la visualización y sacarle un poco más de chicha. HAcer mención a cuales son los modelos más caros y más baratos por ejemplo.

El segundo plot me parece muy interesante aunque quizá repite un poco la info del anterior. Pero comparar las medianas me parece una idea genial.

En el tercer gráfico en la leyenda tienes una gama de color para diferentes años pero tu solo tienes dos. Quizá sería más intuitivo que solo apareciesen esos dos en la leyenda.

Este gráfico quizá no sea el más autoexplicativo y necesite de una explicación algo más extensa para aquellas personas que no están acostumbradas a interpretar gráficos. Pero está genial que te hayas dado cuenta gracias a este gracico que muchos de los productos de 2021 se ajustan a una recta y=x y por tanto eso significa que muchos productos no tienen descuentos. ¡Buena intepretación!

También está bien que menciones que tienes datos desbalanceados. Aunque todos los de 2018 si te fijas están por debajo de la recta, ¿qué signifca esto?¿Podemos sacar alguna conclusión?
