### ISSUE TITLE
Alvaro Fidalgo

### ISSUE THREAD

**Issue by Afidalgo-fmm** [Ironhack-Data-Madrid-Octubre-2021/W3-pipelines-project#26]
https://github.com/Afidalgo-fmm/2-Proyecto

**Comment by Fominayasg** [comment]
Buenas Fidi!! :smile:

El objetivo de este proyecto era ser capaces de crear un `pipeline`. Es decir, una secuencia de `procesos` que se ejecutaran en orden para que ,en nuestro caso, desde un dataframe original obtener otro limpio y enriquecido.

En tu caso veo que no te ha dado tiempo a crear el `pipeline`. Simplemente tienes que crear funciones (en tus archivos.py de la carpeta src) que se ejecuten en orden, la primera tendrá que leer un csv, y la última exportarlo limpio y enriquecido.

Como bonus puedes incluir en el bonus funciones que te generen y exporten visualizaciones a partir de ese nuevo dataset.

Ahora vamos a ir viendo el resto de componentes de tu proyecto.

## Readme

El readme es el archivo que primero se ve al entrar en tu repositorio. Es lo que verán los recruiters y demás personas interesadas en tu proyecto.

Por tanto es importante que sea visualmente atractivo y claro.

En tu caso, este readme es claramente un borrador, mitad en inglés mitad en español.

Para hacer un buen readme debes tener en cuenta lo siguiente:

1. Utilizar el formato markdown. [Aquí](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) está una guía de como escribir en markdown.Es importante utilizar títulos, bullet points, listas, etc. Le dará un aspecto mucho más profesional al readme.
2. Ordénalo en secciones. (Contexto resumido, objetivo del proyecto,origen de los datos, organización del repo y  tecnologias utilizadas).
3. Para las tecnologías utilizadas, te recomiendo que incluyas los links de está manera:

```markdown
In this project we have used the following libraries:
 - [pandas](https://pandas.pydata.org/docs/)
 
 - [numpy](https://numpy.org/doc/stable/)
 
 - [plotly](https://plotly.com/python/)
 
 - [seaborn](https://seaborn.pydata.org/)
 
 - our own "[cleaning_functions.py](www.link_a_tu_archivo_py.es)"
```

Y te quedaría asi:

In this project we have used the following libraries:
 - [pandas](https://pandas.pydata.org/docs/)
 
 - [numpy](https://numpy.org/doc/stable/)
 
 - [plotly](https://plotly.com/python/)
  
 - [seaborn](https://seaborn.pydata.org/)
 
 - our own "[cleaning_functions.py](www.link_a_tu_archivo_py.es)"

## Estructura del repo

La estructura del repo está bastante bien(a pesar de que al main.py y los archivos luego estén vacíos... supongo que lo tienes en "to do"), lo único que cambiaría es meter los jupyters en una carpeta para que tu raíz quede más limpia y ordenada. en el caso de este repo, los jupyters deben ser simplemente archivos donde probar el código antes de juntarlo todo en tu pipeline (main.py)

También puedes numerar los jupyters para que el lector sepa cual debe leer antes o después.

## Limpieza y enriquecimiento

Tienes bastante código repetido asíque todo eso, ya sabes -->>> FUNCIONCITAS!!!

En esta parte del código:
```python
nasdaq = pd.DataFrame(datos)
nasdaq.columns = ['Fecha_NASDAQ','Aper_NASDAQ','Cier_NASDAQ','Max_NASDAQ','Vol_NASDAQ']
nas = pd.DataFrame(dat)
nas.columns = ['Fecha_NASDAQ','Aper_NASDAQ','Cier_NASDAQ','Max_NASDAQ','Vol_NASDAQ']
nasin = pd.DataFrame(datin)
nasin.columns = ['Fecha_NASDAQ','Aper_NASDAQ','Cier_NASDAQ','Max_NASDAQ','Vol_NASDAQ']
nasdan = pd.DataFrame(dataton)
nasdan.columns = ['Fecha_NASDAQ','Aper_NASDAQ','Cier_NASDAQ','Max_NASDAQ','Vol_NASDAQ']
nasdatin = pd.DataFrame(dats)
nasdatin.columns = ['Fecha_NASDAQ','Aper_NASDAQ','Cier_NASDAQ','Max_NASDAQ','Vol_NASDAQ']
nasgul = pd.DataFrame(dato)
nasgul.columns = ['Fecha_NASDAQ','Aper_NASDAQ','Cier_NASDAQ','Max_NASDAQ','Vol_NASDAQ']
nasult = pd.DataFrame(dats)
nasult.columns = ['Fecha_NASDAQ','Aper_NASDAQ','Cier_NASDAQ','Max_NASDAQ','Vol_NASDAQ']
```
Varios consejos:
1. Cuando creas el dataframe puedes incluir directamente el nombre de las columnas, puedes ver la sintaxis en un sitio mágico e inexplorado... :crystal_ball: [LA DOCUMENTACIÓÓÓNNN](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html) :crystal_ball:

2. Para no escribir todas las veces el nombre de las variables, puedes usar una variable que contenga el nombre de las columnas.

Quedaría algo así:
```python
column_names = ['Fecha_NASDAQ','Aper_NASDAQ','Cier_NASDAQ','Max_NASDAQ','Vol_NASDAQ']
nasdaq = pd.DataFrame(dat, columns=column_names)
nasin = pd.DataFrame(datin, columns=column_names)
nasdan = pd.DataFrame(dataton, columns=column_names)
nasdatin = pd.DataFrame(dats, columns=column_names)
nasgul = pd.DataFrame(dato, columns=column_names)
nasult = pd.DataFrame(dats, columns=column_names)
```
Incluso se puede optimizar más creando una función que reciba los datos y los nombres de las columnas, y vaya appendeando o concatenando los dataframe y así te ahorras el siguiente paso.

---

En la función `cambia`, en vez de tantos elifs, puedes usar un diccionario y usarlo para cambiar directamente todos los valores de la columna.

Pero en general muy buen curro con el web csrapping y la api.

Te falta comentar los jupyters para que el lector no se pierda en el código.


## Visualización y conclusiones

El primer gráfico...no entiendo nada... deduzco que cada línea es una moneda pero no sé cual es cual porque no está indicado... y en el eje X deduzco que plotteas los meses por el código pero falta mucha explicación. 

Yo haría mejor un lineplot para ver la evolución anual de las monedas.

Del segundo y tercer plot no entiendo nada de nada... no pones que significan las columnas que plotea ni interpretas el gráfico... Esto lo tienes que completar.

Nuestro trabajo como data analyst va a consistir tanto en conseguir y tratar los datos como en saber interpretarlos y contárselos a los demás.

Ten en cuenta que de cara a un trabajo, la persona a la que le presentes tus resultados no tiene por qué saber nada de plots o datos...

Faltan bastantes cosillas por terminar en el proyecto Fidi, pero va por muy buen camino, para otra hay que gestionar un poco mejor los tiempos.

¡A por el proyecto final!
