### ISSUE TITLE
Eduardo Rivera Proyecto 2

### ISSUE THREAD

**Issue by Eduardo-Rivera98** [Ironhack-Data-Madrid-Octubre-2021/W3-pipelines-project#4]

**Comment by Eduardo-Rivera98** [comment]
https://github.com/Eduardo-Rivera98/Proyecto-NBA.git

**Comment by yamadajc** [comment]
# Proyecto Pipeline
Muy buenas Edu ,
voy a intentar darte todo el feedback con la intención de que realices un cambio positivo, para que mejores todo lo posible.
¡¡Vamos a ello !!

## README

El readme esta correcto. Comentas a la perfección el workflow y la temática invita a seguir leyendo. Pero como consumidor de repositorios me gustaría saber que tecnologías has usado y la fuente de los datos par poder reproducirlo.

## Estructura del repo
En cuanto a la estructura me han faltado algunas cositas en este proyecto. Te dejo por aquí algunas ideas por si te aportan valor de cara al futuro:

-  NO tienes el `.gitignore` en tu repo. Este archivo es esencial (debe ser de lo primero que creemos cuando creamos el repo) ya que en este fichero vamos a almacenar todos los archivos temporales que se nos crean o aquellos archivos que no queremos que se muestren.

- No es recomendable tener archivos con distintas extensiones a la vista. Agrupa los `.py`, `.ipynb`, datos o incluso imagenes de gráficos en carpetas distintas. 

    - Una carpeta de `Notebooks` con los jupyters numerados en el orden que deses que el lector los consuma puede ayudar al orden en nuestro repo.

    - Aunque no tengas ninguna función creada una carpeta `src` es mas que recomendable para tener un notebook limpito donde importemos todas las funciones. 

    - Hubiera estado bien que te crearas una carpeta de `data` donde guardaras todos los datos que importes, cargues o transformes. 


## Sintaxis de código

Tú codigo esta bien. Me faltan comentarios. imagina que no tengo ni idea de scraping pero quiero aprender algo al respecto y llego a tu repo. hazlo accesible para profanos. 
Por lo demás todo lo que haces tienes sentido y no hay "movimientos" innecesarios. Podría ser mas eficiente pero funciona. Lo que si te voy a decir es que tengas cuidado con el nombrado de tus objetos. Recuerda clases en mayusculas funciones en minúsculas y que tengan significado. Listas como `Algo` evitado. 

He visto que cuando haces `df1= pd.read_csv('data/Ultimatedf.csv')`se te cuela la columna `Unnamed: 0`. Eso lo solucionas fácilmente si al guardar el csv `df.to_csv("Ultimatedf.csv", index = False)`o bien en el momento de la carga haces `pd.read_csv("Ultimatedf.csv", index_col=0)`. 



## ToDo
Me faltan funciones, tienes que darle un poco a eso. Podrías empezar con la parte de las conexiones del scraping.
Trabaja un poco el "vender tu repo" con fantasia combinado con algo de estructura de repo y todo bien. 
Felicidades!
