### ISSUE TITLE
lab-pipelines]Carlos_de_León

### ISSUE THREAD

**Issue by Carlosleono** [Ironhack-Data-Madrid-Octubre-2021/W3-pipelines-project#5]
https://github.com/Carlosleono/API-scrapping

**Comment by Fominayasg** [comment]
## Buenas Carlos !! :smile:

El objetivo de este proyecto era ser capaces de crear un `pipeline`. Es decir, una secuencia de `procesos` que se ejecutaran en orden para que ,en nuestro caso, desde un dataframe original obtener otro limpio y enriquecido.

Ahora vamos a ir viendo los diferentes componentes de tu proyecto.

## Readme
El readme tiene los mínimos para cumplir su función pero estaría bien ampliarlo un poco más y darle mejor formato.

Los links a las librerias no funcionan, al menos desde github.

Para mejorarlo puedes tener en cuenta que:

Como ya sabes el readme es vuestra carta de presentación y por tanto es importante prestarle atenció.

Este readme está muy pobre.. sirve para que el proyecto cuente como entregado pero lo tienes que cambiar.

Puedes tener en cuenta lo siguiente:

1. Utilizar el formato markdown. [Aquí](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) está una guía de como escribir en markdown.Es importante utilizar títulos, bullet points, listas, etc. Le dará un aspecto mucho más profesional al readme.
2. Ordénalo en secciones. (Contexto resumido, objetivo del proyecto,origen de los datos, organización del repo y  tecnologias utilizadas).
3. Para las tecnologías utilizadas, te recomiendo que incluyas los links de está manera:

```markdown
In this project we have used the following libraries:
 - [pandas](https://pandas.pydata.org/docs/)
 
 - [numpy](https://numpy.org/doc/stable/)
 
 - [plotly](https://plotly.com/python/)
 
 - [seaborn](https://seaborn.pydata.org/)
 
 - our own "[cleaning_functions.py](www.link_a_tu_archivo_py.es)"
```

Y te quedaría asi:

In this project we have used the following libraries:
 - [pandas](https://pandas.pydata.org/docs/)
 
 - [numpy](https://numpy.org/doc/stable/)
 
 - [plotly](https://plotly.com/python/)
  
 - [seaborn](https://seaborn.pydata.org/)
 
 - our own "[cleaning_functions.py](www.link_a_tu_archivo_py.es)"

## Estructura del repo

La estructura está bien construida. Lo único es que has llamado a tu archivo de funciones `functions.py`  AAAYYYYYYSYSSSSSS!!!!!

Las funciones del archivo.py están documentadas pero yo lo ampliaría un poco más- Por ejemplo, aquí:
```This function gets a table and returns a dataframe```, especificaría que es una tabla extraída de un html (lo deduzco por las etiquetas tr y td y porque conozco el proyecto pero si no sería muy dificil saberlo a primera vista)

Enel caso de la función:
```python
def tofloat(x):
    '''This function changes a pandas series to float
    '''

    return x.astype(float)
```

No hace falta crear una función para algo que ya existe... es decir, ya hay una función que cambia valores a float, que es la que incluyes en tu función. Por tanto es un poco redundante volver a definirla.

## Enriquecimiento del dataset

El enriquecimiento de los datos está muy bien, tiene sentido y nos aporta valor al análisis ¡Enhorabuena!

## Pipeline

Te dejo algunos comentarios sobre el código del pipeline directamente en el archivo, pero en general está muy bien, veo que has comprendido la función del pipeline. Faltaría que lo ejecutaras en un jupyter para ver que todo funciona ya que el final enseña los plots pero no los guarda, por tanto necesitamos verlo en agún sitio.


## Notebooks

Sé que uno al menos es para hacer pruebas pero ese print infinito de una response...††††††† Mátame camión!!!:truck:

En el de análisis, me falta la conclusión final y explicción de las gráficas. Por tro lado tienes un poco de código repetido ¿Crees que podrías hacerlo más eficiente?

El análisis de los datos en sí super currado y muy bien pensado. ¡Enhorabuena! 


En general buen trabajo Carlos, falta pulir algunos detalles pero está muy muy bien.
