### ISSUE TITLE
Proyecto Apis-Roberto Alonso

### ISSUE THREAD

**Issue by Roblak96** [Ironhack-Data-Madrid-Octubre-2021/W3-pipelines-project#6]
https://github.com/Roblak96/Repositorio-Lol.git

**Comment by yamadajc** [comment]
# Proyecto Pipeline
Muy buenas Roberto.
Voy a intentar darte todo el feedback con la intención de que realices un cambio positivo, para que mejores todo lo posible.

## README

El contenido del readme esta correcto. Dejas clarísimo el objetivo del proyecto y el workflow que vas a seguir. Si hubieses puesto la tecnología usada y la fuente de tus datos con enlaces para seguir a la perfección tu proyecto hubiese estado de 10. Por otro lado me gusta el toque retro que le da el formato .txt pero eso te limita para la edición y el enriquecer la información enriquecimiento del contenido. 

Es por eso que te dejo una guía de markdow 👉 [aquí](https://www.markdownguide.org/cheat-sheet/) 


## Estructura del repo

La estructura me han faltado algunas cositas en este proyecto. Te dejo por aquí algunas ideas por si te aportan valor de cara al futuro:

- Me parece que solo has hecho un commit y no pasa nada. Pero sabias que en el feed de tu perfil aparece un gráfico con el numero de commits que haces y este adquiere un color más intenso cuántos mas commits hagas. Pero sobre todo y lo mas importante es que con cada commit que hagas tendrás una copia a la que recurrir por si se te cae una taza de cafe sobre el teclado. 

- NO tienes el `.gitignore` en la raiz de tu repo. Por algún motivo esta en `.src`. Este archivo es esencial (debe ser de lo primero que creemos cuando creamos el repo) ya que en este fichero vamos a almacenar todos los archivos temporales que se nos crean o aquellos archivos que no queremos que se muestren. Por ejemplo `.ipynb_checkpoints` un directorio completo que no queremos que se suba. 

- No es recomendable tener archivos con distintas extensiones a la vista. Agrupa los `.py`, `.ipynb`, datos o incluso imagenes de gráficos en carpetas distintas. 

    - Una carpeta de `Notebooks` con los jupyters numerados en el orden que desee que el lector los consuma puede ayudar al orden en nuestro repo. En él podrías haber metido `Web Scraping LOL.ipynb` y  `Visualización.ipynb`.

    - Me has creado una carpeta `src`, así que genial. Es la forma mas recomendable para tener un notebook limpito donde importemos todas las funciones. En tu caso tenemos `api_cleaning.py`y `api_functions.py` pero ninguna de ellas tiene nada. ¿Se te paso subirlas?

    - También has creado una carpeta `data` en la que has metido un csv. Así que genial. 




- Tu `main.py` no tiene contenido ... Se te olvido actualizar ? Recuerda que el objetivo de este proyecto era que creaseis un ejecutable que hiciese cosas de forma automática. 



## Sintaxis de código

Como le he dicho a Luis, ojo con librerías que importas hay algunas que no las usas como `dotenv` o `time`. 

El código no llega a los requerimientos que se pidieron para este proyecto. 

`Web Scraping LOL.ipynb` hace una captura de datos pero no llegas a guardarlos. El caso es que cuando miro `Visualización.ipynb` tan solo me ploteas un histograma.


## Feed back 

También he estado en la situación en la que las cosas no salen a la primera. En este proyecto te han faltado puntos críticos. Estoy seguro de que puedes gestionarlo y al final sacaras las cosas adelante.
