### ISSUE TITLE
[W3--proyecto-de-cine-y-pipes] - Guillermo Perinat 

### ISSUE THREAD

**Issue by Pnat1** [Ironhack-Data-Madrid-Octubre-2021/W3-pipelines-project#7]
https://github.com/Pnat1/W3--proyecto-de-cine-y-pipes

**Comment by AnaAGG** [comment]
# Proyecto Pipeline

Hola hola Guille 🙋🏻‍♀️ ya estoy por aquí otra vez! Pero esta vez te vengo a contar cositas sobre tu proyecto de pipelines 🚀.

## README

Respecto al readme... vamos a aceptar pulpo como animal de compañía 😂. Por que en realidad no tienes readme! Y todos sabemos lo que pasa si entregamos un proyecto sin readme. Es considerado como no enviado, y para graduarnos necesitamos tener entregados TODOS los proyectos. 

Tienes escrito cual es la estructura del readme, sabes como se hace, por lo tanto no te digo nada. 

Pero recuerda, el readme es lo primero que se va a ver de nuestro repo, donde demostramos nuestra capacidad de síntesis y orientamos al lector que es lo que se hace en el proyecto y que se va a encontrar. 

Plis 🙏, en cuanto tengas un hueco hazlo, más por ti que por nosotras 😊. 
## Estructura del repo

Vamos con la estructura del repo, que tengo que decir que no esta especialmente ordenado. Pero te dejo por aquí unos *tips* por si te aportan valor para el futuro. 

- Crearnos una carpeta de `notebooks` donde almancenaremos todas los jupyters sobre los que hemos trabajado. Además, podemos numerarlos para indicar el orden de trabajo. 

- Crearnos una carpeta `src`, en esta carpeta iremos metiendo los distintos archivos `.py` donde tendremos las funciones  que usaremos en el jupyter. 

- Una carpeta de `data` donde guardaremos todos los ficheros de datos que nos descargemos o generemos de las llamadas a la API.

- Una carpeta que se llame `images` donde guardaremos todas las imagenes generadas en el proyecto. 

- El `.gitignore` donde tendremos todos aquellos archivos que no queremos que se suban a repo o que no son útiles. ¿Qué archivos serán estos? 
  - .ipynb_checkpoints
  - __pycache__
  - jupyters que no queramos que se vean
  - etc.


- Otra cosa, tienes una archivo que se llama `clean_functions` que esta básicamente vacía, lo único que tienes son un montón de *imports*. Ese tipo de archivos o lo eliminamos o lo metemos en el `.gitignore`. 


## Sintaxis de código

Vamos con el código! 

- Lo primero de todo, tienes una función que se llama `pescamos_titulos_peliculos`, suuuper bien que te crearas una función. Solo como detalle, no te olvides de los *docstrings*  en la funciones!
 
    ¿Qué es lo que tiene que tener un docstring?   
        - Qué es lo que hace la función  
        - Qué argumentos recibe  
        - Qué es lo que devuelve  

    [Aquí](https://www.python.org/dev/peps/pep-0257/) algo de info sobre los docstrings . 

    ```python
    def mifuncion(argumento1, argumento2):
        '''
        Lo que hace la función
        args: 
            argumento1: tipo de dato
            argumento2: tipo de dato
        return:
            que nos devuelve la función
        '''
        return "Hola"
    ```
- Ojo con los *prints* demasiado largos, tienes uno en el jupyter de `PORAHORA`
- ¿Qué pasó con este fichero `main_pipeline.py.ipynb`? Esta completamente vacío 😔

Te descargas dos `csv`, los limpias y los concatenas para tener una información bastante completa. Buen trabajo por esta parte Guille. 

Además, haces *scrapeo* de una página web de la que sacas alguna información para aportar valor a tus `csv` anteriores. 

Aún así, este proyecto ha quedado un pelín flojito. Te dejo por aquí unos *tips* de las cosas que nos faltan en este proyecto:

- En ningún momento has hecho una conexión entre los datos de los `csv` y los del *scrapeo* lo cual era uno de los principales objetivos de este proyecto. 
- Tampoco has incluido la parte de la visualización para la extracción de conclusiones 😔, también puento obligatorio del proyecto. 

Sin embargo tienes muy buen código de lo que tienes hecho, solo nos ha faltado meterlo en funciones. 

## TODOs

¿Qué es lo que pasó con este proyecto Guille? Tuviste algún problema? Si necesitas hablar sobre este proyecto dinoslo y te intentamos ayudar. La verdad es que poco más te puedo decir sobre el proyecto porque tenemos poco contenido 😔

Venga ánimo Guille, y ya me dices 😉! 

![image](https://user-images.githubusercontent.com/75084991/143215885-62e0a68a-c880-4359-8336-9a90e256fea5.png)

**Comment by Pnat1** [comment]
Buenas noches Ana,

Te agradezco muchísimo la extensa corrección. Este fin de semana pasado
estuve trabajando en este proyecto que se me quedó bastante rana y he
tenido un error de principiante al no hacer git commit.
Tenéis toda la razón que esto es para mí y tengo que esforzarme más. He
tenido algunas semanas de estar muy atascado y no saber por dónde tirar.
¡Gracias por los consejos, los pondré en práctica!

Guille
