### ISSUE TITLE
[Ester Fernández] pipelines

### ISSUE THREAD

**Issue by emarfer** [Ironhack-Data-Madrid-Octubre-2021/W3-pipelines-project#8]
https://github.com/data2021oct/Pipelines-project

**Comment by AnaAGG** [comment]
# Proyecto Pipeline

Hola hola Ester 🙋🏻‍♀️ ya estoy por aquí otra vez! Pero esta vez te vengo a contar cositas sobre tu proyecto de pipelines 🚀.

## README

Menudo readme te has marcado Ester! Esta increíble, pero ya sabes que siempre tenemos que comentar algo jejejej. Solo un detalle para que este readme te quede perfecto: 

- Me han faltado las lbrerías que has usado en el proyecto y los links a la documentación oficial. 

Por el resto, 🔝🔝

## Estructura del repo

De nuevo Ester, un trabajo impecable en la organización del repo. Solo como detalles por si te aportan valor de cara al futuro: 

- Se te ha pasado un archivo temporal dentro de la carpeta de `src`, el archivo `__pycache--`. Recuerda, todos estos archivos temporales rarinchis, al `.gitignore`. 

- Suuper bien que no se te haya quedado el token de la API a la vista 💪. 

- Por ponerme quisquillosa, si en la carpeta notebooks numeras los notebooks para saber cual es el orden de ejecución te queda suuper cerrada la organización del repo. 


## Sintaxis de código

Vamos con la parte de código 🚀:

- Vamos a empezar con los *docstrings*, genial que los hayas incluido en todas tus funciones. Supongo que ya te lo habrán comentado en otra corrección, lo sé soy muy turras! Pero me voy a poner un poco quisquillosa con ellos.

   ¿Qué es lo que tiene que tener un docstring?   
    - Qué es lo que hace la función  
    - Qué argumentos recibe  
    - Qué es lo que devuelve
    - Y lo más importante es que tiene que estar dentro de la función.   

    [Aquí](https://www.python.org/dev/peps/pep-0257/) algo de info sobre los docstrings . 

    ```python
    def mifuncion(argumento1, argumento2):
        '''
        Lo que hace la función
        args: 
            argumento1: tipo de dato
            argumento2: tipo de dato
        return:
            que nos devuelve la función
        '''
        return "Hola"
    ```
- Vamos con la función `num_string`. 

    Genial que te crearas una función para conventir un int a string

    ```python
    def num_string(dato):
    
        if type(dato)== int:
            return str(dato)
        else:
            return dato
    ```
    Pero... tienes sentido esto cuando tenemos un método en pandas que nos lo hace? Mejor usar los propios métodos: 

    ```python
    def num_string(dato):
        try: 
            return df["Album"].astype(dtype=object)
        else:
            return dato
    ```
- Si esto me lo haces en una función quedaría completamente perfecto Ester

    ```python
    stone["Gen"] = stone["Genre"].str.extract(r"(^([^,])+)")[0]
    stone["Subgenre"] = stone["Genre"].str.extract(r",\s*(.*$)")[0]
    # podemos crear una función que reciba como parámetro el patrón de la columna. Luego, como tenemos dos parámetros en la función tendremos que usar un apply y un lambda.
    ```
- Lo mismo en esta parte del código: 

    ```python
        stone.Album = stone.Album.str.replace(r'(Metallica...The Black Album..)',"Metallica",regex=True)
    stone.Album = stone.Album.str.replace(r'(Eagles...st album.)',"Eagles",regex=True)
    stone.Artist = stone.Artist.str.replace("Neil Young with Crazy Horse","Neil Young & Crazy Horse",regex=True)
    stone.Artist = stone.Artist.str.replace(r"(Bob Dylan...The Band)","Bob Dylan And The Band",regex=True)
    stone.Artist = stone.Artist.str.replace(r"(Prince\s+.*)","Prince & The Revolution",regex=True)
    stone.Artist = stone.Artist.str.replace(r"(Rufus...Chaka Khan)","Rufus",regex=True)
    stone.Album = stone.Album.str.replace(r'(Proud Mary.*)',"Best Of / Proud Mary",regex=True)
    stone.Artist = stone.Artist.str.replace(r'(.*The Velvet Underground.*)',"The Velvet Underground",regex= True)
    stone.Artist = stone.Artist.str.replace("‐","-",regex = True)
    stone.Album = stone.Album.str.replace("‐","-",regex = True)
    stone.Gen = stone.Gen.str.replace("piunk","punk",regex = True)
    stone.Gen = stone.Gen.str.replace("punk rock","punk",regex = True)
    stone.Gen = stone.Gen.str.replace("folk rock","folk",regex = True)

    # Nos podemos hacer una funcion para Album. otra para Artist y otra para género

    # Haciendo un poco de pseudocodigo, no sé si es funcional pero la idea iría por ahí: 

    def replace_album(x):
        diccionario = {"Metallica": "Metallica",
                        "Eagles": "Eagles" ...}

        for key, value in diccionario.items():
            if key in x:
                return x.replace(key, value)
            else:
                return x
    stone.Album = stone.Album.apply(replace_album)
    ```
- Esto: 

    ```python
    df = stone

    # esto de cara a las convenciones de python es raro. Recuerda que tenemos el método `copy`
    df = stone.copy()
    ```
- Por seguir poniendome quisquillosa y que tu proyecto vaya quedando cerradito, cuando haces la llamada a la API de last_fm tienes estas lineas de código

    ```python
    url_last50 = f"http://ws.audioscrobbler.com/2.0/?method=chart.gettopartists&api_key={apikey}&format=json"
    req_last50 = requests.get(url_last50).json()
    last_50 = req_last50["artists"]["artist"]
    last_top50 = pd.DataFrame.from_dict(last_50)

    # lo ideal, que fuera todo a una función y que la llamaramos desde el .py. El main debe estar lo más limpio de código posible 

    def api_lastfm(apikey):
        url_last50 = f"http://ws.audioscrobbler.com/2.0/?method=chart.gettopartists&api_key={apikey}&format=json"
        req_last50 = requests.get(url_last50).json()
        last_50 = req_last50["artists"]["artist"]
        return pd.DataFrame.from_dict(last_50)
    ```
- Lo mismo podemos hacer con el `topsells`

    ```python
    def topsells (url):
    
        html_insider = requests.get(url)
        soup_insider = BeautifulSoup(html_insider.content,"html.parser")
        tags_insider = soup_insider.find_all("div", {"class": "slide-layout"})

        insider_data = scap.data_scrap(tags_insider)
        return pd.DataFrame(insider_data)
    # Una de las cosas más interesantes es que podemos tener funciones que llamen a otras funciones, haciendo que nuestro código este muy anidadito y con un flujo de trabajo muy claro 🤓
    ```
- No he visto completamente tus datos, pero cuando en los datos de `topsells` haces el reemplazo de los valores nulos para algunas columnas. Esas columnas son todas las columnas que tienen NaN. En caso de que sea así recuerda que lo podemos hacer del tirón


    ```python
    top_sell_rs.Number.fillna(0,inplace = True)
    top_sell_rs.Year.fillna(0,inplace = True)
    top_sell_rs.Type.fillna("unknown",inplace = True)
    top_sell_rs.Rating.fillna(0,inplace = True)
    top_sell_rs.Gen.fillna("none",inplace = True)
    top_sell_rs.playcount.fillna(0,inplace = True)
    top_sell_rs.listeners.fillna(0,inplace = True)

    # lo ideal es que lo hagas de una sola vez o a todo el dataframe a la vez o a todas esas columnas seleccionandolas 
     top_sell_rs[["col1", "col2", "etc"]].fillna(0,inplace = True)
    ```
La parte de visualización me encanta Ester, esta super bien trabajanda, con una extracción de conclusiones super clara y los gráficos muy bien usados. Muy buen trabajo

## TODOs    

Bueno Ester, trabajo INCREIBLE en este proyecto, deberías estar orgullosa. Se que te mando una corrección normal, pero es que soy muy turras jajaja. Te dejo por aquí un recap de los puntos más importantes:

- Los archivos temporales rarinchis que se nos generan, todos al `.gitignore`
- Los *docstrings* de las funciones
- Atomizar un poco el código y evitar estructuras altamente repetidas. 


Aún con todo, super trabajazo Ester 🔥🔥🔥. 

![image](https://user-images.githubusercontent.com/75084991/143031392-d2941f33-1b0c-41c4-9c6c-48aab04078bf.png)
