### ISSUE TITLE
[Dani Helguera] W3-pipelines-project

### ISSUE THREAD

**Issue by Danihelguera** [Ironhack-Data-Madrid-Octubre-2021/W3-pipelines-project#9]
https://github.com/Danihelguera/W3-Project-DaniHelguera.git

**Comment by Fominayasg** [comment]
Buenas Dani!! :smile:

El objetivo de este proyecto era ser capaces de crear un `pipeline`. Es decir, una secuencia de `procesos` que se ejecutaran en orden para que ,en nuestro caso, desde un dataframe original obtener otro limpio y enriquecido.

Ahora vamos a ir viendo los diferentes componentes de tu proyecto.

## README

El archivo Readme.md está super currado y muy bien organizado pero se corresponde más con una guía de como hacer el proyecto que con un Readme en sí. (Pero lo que es el archivo está super bien escrito, guárdalo por ahí para acordarte de lo que tenias que hacer, el Dani del futuro te lo agradecerá)

El readme es la presentación de contenido de tu proyecto. Puedes hacer algo así:

1. Es importante poner un título descriptivo(usando # para ponerlo como header, puedes ver el formato de markdown [aquí](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)).

2. Introducción y justificación del proyecto.
Yo la pondría justo después del título.

3. Sección hipótesis en la que listes tu hipótesis, enunciadas como tal. Una frase concisa por hipótesis.

3. Para explicar como has organizado el jupyter yo pondría una sección (más ## para header con menor rango) "Estructutura del repositorio" en el cuál pongas una lista con los aprtados de tu repo y una explicación breve (5 o 6 palabras) de lo que contienen.

4. Estaría bien mencionar el origen de los datos (con link a la páginas de kaggle o de dónde lo hayas sacado)

5. Por último te faltaría el technology stack. Es decir un apartado en el que digas que librerías has utilizado y el link a la documentación de cada una. Puedes hacer algo así:
```markdown
In this project we have used the following libraries:
 - [pandas](https://pandas.pydata.org/docs/)
 
 - [numpy](https://numpy.org/doc/stable/)
 
 - [plotly](https://plotly.com/python/)
 
 - [seaborn](https://seaborn.pydata.org/)
```

Y te quedaría asi:

In this project we have used the following libraries:
 - [pandas](https://pandas.pydata.org/docs/)
 
 - [numpy](https://numpy.org/doc/stable/)
 
 - [plotly](https://plotly.com/python/)
  
 - [seaborn](https://seaborn.pydata.org/)

Con todo esto tienes un readme completo, si tu consideras que se necesita algo más o algo menos por supuesto lo adaptas a las necesidades de tu proyecto concreto.

## Estructura del repositorio

El repositorio está muy bien organizado. Como pequeño tip te diría que metas los notebooks de limpieza y consultas a la api en otra carpeta, ya que realmente son pruebas, y tu codigo final va a ser el pipeline que tienes en main.py

## Enriquecimiento

El enriquecimiento del dataset era una de las tareas más importantes del proyecto.

Tu enriquecimiento utilizando la API de la AEMET es muy interesante ya que podemos suponer que las condiciones meteórologicas probablemente afecten a la cantidad de siniestro que se producen. Sin embargo luego no relacionas esta información con tu primer dataset. Entonces acabamos con la misma información que si no lo hubieramos enriquecido...

De cara a futuro intenta unir los dataframes basándote en las fechas que lo tienes en ambos, y tener un dataframe de siniestros en el que tengas columnas que te digan por ejemplo si llueve o no... 

Es una pena que te hayas currado tu función para extraer un montón de datos de datos de la API y luego no lo utilices.

# Cleaning

La limpieza funciona y nos deja un dataset con el que se puede trabajar cómodamente, pero podemos hacerla de manera más eficiente.

Respecto a las funciones de cleaning_functions.py no tienes ninguna documentada. Es importante hacerlo para que cualquier persona que lo vea sepas a primera vista que hace esa función sin tener que intentar avriguarlo a través de tu código. Algo así:
```python
def suma(a,b):
    '''Está función toma como argumentos dos integers y devuelve la suma de ambos'''
    return a+b
```
Por otro lado tienes 3 funciones para traducir en las que tienes que picar uno a uno los elementos y su traducción.

Para hacerlo más eficiente puedes utilizar directamente la librería de *Google translator* --> [googletrans]
(https://pypi.org/project/googletrans/)

Además de esta manera aunque en un futuro se actualizasen los datos  de tu dataset, tu proyecto seguiría funcionando. Haciéndolo uno a uno en cuanto se meta un valor diferente ya no sirve.

Las funciones para tranformar las horas en franjas del día son super buena idea para el posterior análisis. Muchas veces nos será muy útil transformar nuestras columnas y no solo limpiarlas.


## Pipeline

Tu archivo main.py es un ejemplo de como hacer un pipeline limpio y entendible ¡enhorabuena! Se nota que has entenido su utilidad.

Además has incluido varios prints de control para que cuando lo ejecutemos en la terminal vatas pudiendo comprobar que todo va bien.

Super buen trabajo Dani!

## Análisis y conclusiones

El análisis está genial también. Se nota se has dedicado tiempo a pensar cual sería un análisis útil de tus datos, y en las explicaciones de tus conclusiones tienes cuidado de ser preciso y dejar claro si para afirmar ciertas cosas hacen falta otros datos. La verdad que me ha gustado mucho.

En general los plots están bien elegidos, si quieres ir un paso más allá te recomiendo que eches un ojo a las paletas de color para hacerlos más intuitivos.

El mapa de calor es una idea fantástica y que cuadra mucho con la naturaleza de tus datos. ¡Top!


Muy buen trabajo en general Dani!! Termina la parte de los datos climatológicos y lo dejas ya perfect.
